// ── Types ─────────────────────────────────────────────────────────────────────

export type BirdHabitat =
  | "도시"
  | "어촌"
  | "온천산"
  | "숲"
  | "꽃밭"
  | "물가"
  | "바닷가"
  | "초원"
  | "해안"
  | "새들의 복귀"
  | "기타";

export interface Bird {
  id: string;
  emoji: string;
  thumbnail?: string;
  name: string;
  ko: string;
  desc?: string;
  level: number;
  weathers: string[];
  times: string[];
  location: string;
  distance: number;
}

export interface BirdGrade {
  stars: number;
  sellPrice: number;
  sellEventPrice: number;
}

export interface BirdDetail extends Bird {
  habitat: BirdHabitat;
  rarity: string;
  sellMin: number;
  sellMax: number;
  grades: BirdGrade[];
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function grades(prices: [number, number, number, number, number]): BirdGrade[] {
  return prices.map((price, i) => ({
    stars: i + 1,
    sellPrice: price,
    sellEventPrice: 0,
  }));
}

// ── Data ──────────────────────────────────────────────────────────────────────

export const BIRDS: BirdDetail[] = [
  // Lv.1
  {
    id: "european-robin",
    emoji: "🐦",
    name: "European Robin",
    thumbnail: "/images/birds/european_robin.png",
    ko: "꼬까울새",
    level: 1,
    habitat: "도시",
    rarity: "일반",
    location: "도시",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 7,
    sellMax: 224,
    grades: grades([7, 30, 60, 112, 224]),
  },
  {
    id: "great-tit",
    emoji: "🐦",
    name: "Great Tit",
    thumbnail: "/images/birds/great_tit.png",
    ko: "노랑배박새",
    level: 1,
    habitat: "온천산",
    rarity: "일반",
    location: "온천산",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 7,
    sellMax: 224,
    grades: grades([7, 30, 60, 112, 224]),
  },
  {
    id: "wren",
    emoji: "🐦",
    name: "Wren",
    thumbnail: "/images/birds/wren.png",
    ko: "굴뚝새",
    level: 1,
    habitat: "숲",
    rarity: "일반",
    location: "숲",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 7,
    sellMax: 224,
    grades: grades([7, 30, 60, 112, 224]),
  },
  {
    id: "eurasian-bullfinch",
    emoji: "🐦",
    name: "Eurasian bullfinch",
    thumbnail: "/images/birds/eurasian_bullfinch.png",
    ko: "멋쟁이새",
    level: 1,
    habitat: "도시",
    rarity: "일반",
    location: "도시 근교",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 7,
    sellMax: 224,
    grades: grades([7, 30, 60, 112, 224]),
  },
  {
    id: "common-chaffinch",
    emoji: "🐦",
    name: "common chaffinch",
    thumbnail: "/images/birds/common_chaffinch.png",
    ko: "푸른머리되새",
    level: 1,
    habitat: "꽃밭",
    rarity: "일반",
    location: "꽃밭",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 7,
    sellMax: 224,
    grades: grades([7, 30, 60, 112, 224]),
  },
  {
    id: "blue-and-yellow-macaw",
    emoji: "🐦",
    name: "Blue-and-yellow Macaw",
    thumbnail: "/images/birds/blue_and_yellow_macaw.png",
    ko: "청금강앵무",
    level: 1,
    habitat: "새들의 복귀",
    rarity: "일반",
    location: "새들의 복귀 사건",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 7,
    sellMax: 224,
    grades: grades([7, 30, 60, 112, 224]),
  },
  {
    id: "stock-dove",
    emoji: "🕊️",
    name: "Stock Dove",
    thumbnail: "/images/birds/stock_dove.png",
    ko: "분홍가슴비둘기",
    level: 1,
    habitat: "도시",
    rarity: "일반",
    location: "도심",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 10,
    sellMax: 320,
    grades: grades([10, 40, 80, 160, 320]),
  },
  {
    id: "eurasian-collared-dove",
    emoji: "🕊️",
    name: "Eurasian collared Dove",
    thumbnail: "/images/birds/eurasian_collared_dove.png",
    ko: "염주비둘기",
    level: 1,
    habitat: "기타",
    rarity: "일반",
    location: "홈",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 10,
    sellMax: 320,
    grades: grades([10, 40, 80, 160, 320]),
  },
  {
    id: "speckled-dove",
    emoji: "🕊️",
    name: "Speckled Dove",
    thumbnail: "/images/birds/speckled_dove.png",
    ko: "얼룩비둘기",
    level: 1,
    habitat: "어촌",
    rarity: "일반",
    location: "어촌",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 10,
    sellMax: 320,
    grades: grades([10, 40, 80, 160, 320]),
  },
  {
    id: "greater-flamingo",
    emoji: "🦩",
    name: "Greater Flamingo",
    thumbnail: "/images/birds/greater_flamingo",
    ko: "큰홍학",
    level: 1,
    habitat: "물가",
    rarity: "일반",
    location: "물가",
    distance: 4,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 15,
    sellMax: 480,
    grades: grades([15, 60, 120, 240, 480]),
  },
  {
    id: "blue-peafowl",
    emoji: "🦚",
    name: "Blue Peafowl",
    thumbnail: "/images/birds/blue_peafowl.png",
    ko: "청공작",
    level: 1,
    habitat: "새들의 복귀",
    rarity: "일반",
    location: "새들의 복귀 사건",
    distance: 5,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 10,
    sellMax: 320,
    grades: grades([10, 40, 80, 160, 320]),
  },
  {
    id: "mallard",
    emoji: "🦆",
    name: "Mallard",
    thumbnail: "/images/birds/mallard.png",
    ko: "청둥오리",
    level: 1,
    habitat: "물가",
    rarity: "일반",
    location: "호수",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 12,
    sellMax: 400,
    grades: grades([12, 50, 100, 200, 400]),
  },
  {
    id: "long-tailed-tit",
    emoji: "🐦",
    name: "Long-tailed Tit",
    thumbnail: "/images/birds/long_tailed_tit.png",
    ko: "오목눈이",
    level: 1,
    habitat: "기타",
    rarity: "일반",
    location: "블랑코 머리 위",
    distance: 2,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 2,
    sellMax: 64,
    grades: grades([2, 8, 16, 32, 64]),
  },
  // Lv.2
  {
    id: "eurasian-nuthatch",
    emoji: "🐦",
    name: "Eurasian Nuthatch",
    thumbnail: "/images/birds/eurasian_nuthatch.png",
    ko: "동고비",
    level: 2,
    habitat: "어촌",
    rarity: "일반",
    location: "어촌",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 10,
    sellMax: 320,
    grades: grades([10, 40, 80, 160, 320]),
  },
  {
    id: "bearded-reedling",
    emoji: "🐦",
    name: "Bearded Reedling",
    thumbnail: "/images/birds/bearded_reedling.png",
    ko: "수염오목눈이",
    level: 2,
    habitat: "온천산",
    rarity: "일반",
    location: "온천산",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 10,
    sellMax: 320,
    grades: grades([10, 40, 80, 160, 320]),
  },
  {
    id: "woodchat-shrike",
    emoji: "🐦",
    name: "Woodchat Shrike",
    thumbnail: "/images/birds/woodchat_shrike.png",
    ko: "빨간머리때까치",
    level: 2,
    habitat: "도시",
    rarity: "일반",
    location: "도시 근교",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 10,
    sellMax: 320,
    grades: grades([10, 40, 80, 160, 320]),
  },
  {
    id: "wonga-pigeon",
    emoji: "🕊️",
    name: "Wonga Pigeon",
    thumbnail: "/images/birds/wonga_pigeon.png",
    ko: "웡가비둘기",
    level: 2,
    habitat: "숲",
    rarity: "일반",
    location: "숲",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 15,
    sellMax: 480,
    grades: grades([15, 60, 120, 240, 480]),
  },
  {
    id: "pink-necked-green-pigeon",
    emoji: "🕊️",
    name: "Pink-necked Green Pigeon",
    thumbnail: "/images/birds/pink_necked_green_pigeon.png",
    ko: "분홍목녹색비둘기",
    level: 2,
    habitat: "꽃밭",
    rarity: "일반",
    location: "꽃밭",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 15,
    sellMax: 480,
    grades: grades([15, 60, 120, 240, 480]),
  },
  {
    id: "eurasian-wigeon",
    emoji: "🦆",
    name: "Eurasian Wigeon",
    thumbnail: "/images/birds/eurasian_wigeon.png",
    ko: "홍머리오리",
    level: 2,
    habitat: "물가",
    rarity: "일반",
    location: "강",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 17,
    sellMax: 544,
    grades: grades([17, 70, 140, 280, 544]),
  },
  {
    id: "seagull",
    emoji: "🐦",
    name: "Seagull",
    thumbnail: "/images/birds/seagull.png",
    ko: "바다갈매기",
    level: 2,
    habitat: "바닷가",
    rarity: "일반",
    location: "해변",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 17,
    sellMax: 544,
    grades: grades([17, 70, 140, 280, 544]),
  },
  // Lv.3
  {
    id: "eurasian-golden-oriole",
    emoji: "🐦",
    name: "Eurasian Golden Oriole",
    ko: "유럽꾀꼬리",
    thumbnail: "/images/birds/eurasian_golden_oriole.png",
    level: 3,
    habitat: "기타",
    rarity: "일반",
    location: "가정",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 15,
    sellMax: 480,
    grades: grades([15, 60, 120, 240, 480]),
  },
  {
    id: "green-magpie",
    emoji: "🐦",
    name: "Green Magpie",
    ko: "녹자작",
    level: 3,
    habitat: "어촌",
    rarity: "일반",
    location: "어촌 등대",
    distance: 2,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 15,
    sellMax: 480,
    grades: grades([15, 60, 120, 240, 480]),
  },
  {
    id: "black-throated-tit",
    emoji: "🐦",
    name: "Black-throated Tit",
    ko: "검은턱오목눈이",
    level: 3,
    habitat: "숲",
    rarity: "일반",
    location: "숲속 점프대",
    distance: 2,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 15,
    sellMax: 480,
    grades: grades([15, 60, 120, 240, 480]),
  },
  {
    id: "scarlet-macaw",
    emoji: "🐦",
    name: "Scarlet Macaw",
    ko: "홍금강앵무",
    level: 3,
    habitat: "새들의 복귀",
    rarity: "일반",
    location: "새들의 복귀 사건",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 10,
    sellMax: 320,
    grades: grades([10, 40, 80, 160, 320]),
  },
  {
    id: "ruddy-shelduck",
    emoji: "🦆",
    name: "Ruddy Shelduck",
    thumbnail: "/images/birds/ruddy_shelduck.png",
    ko: "황오리",
    level: 3,
    habitat: "기타",
    rarity: "일반",
    location: "근교 호수",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 12,
    sellMax: 400,
    grades: grades([12, 50, 100, 200, 400]),
  },
  {
    id: "king-eider",
    emoji: "🦆",
    name: "King eider",
    thumbnail: "/images/birds/king_eider.png",
    ko: "호사북방오리",
    level: 3,
    habitat: "물가",
    rarity: "일반",
    location: "강",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 17,
    sellMax: 544,
    grades: grades([17, 70, 140, 280, 544]),
  },
  {
    id: "audouins-gull",
    emoji: "🐦",
    name: "Audouin's Gull",
    ko: "오두앵갈매기",
    level: 3,
    habitat: "기타",
    rarity: "일반",
    location: "고래바다 해변",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 17,
    sellMax: 544,
    grades: grades([17, 70, 140, 280, 544]),
  },
  {
    id: "european-shag",
    emoji: "🐦",
    name: "European shag",
    thumbnail: "/images/birds/european_shag.png",
    ko: "유럽가마우지",
    level: 3,
    habitat: "바닷가",
    rarity: "일반",
    location: "바다",
    distance: 4,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 17,
    sellMax: 544,
    grades: grades([17, 70, 140, 280, 544]),
  },
  // Lv.4
  {
    id: "pied-wagtail",
    emoji: "🐦",
    name: "Pied Wagtail",
    ko: "알락할미새",
    level: 4,
    habitat: "바닷가",
    rarity: "일반",
    location: "보라색 해변",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 15,
    sellMax: 480,
    grades: grades([15, 60, 120, 240, 480]),
  },
  {
    id: "grey-headed-rosefinch",
    emoji: "🐦",
    name: "Grey-headed Rosefinch",
    ko: "회색머리붉은참새",
    level: 4,
    habitat: "어촌",
    rarity: "일반",
    location: "어촌광장",
    distance: 3,
    times: ["상시"],
    weathers: ["맑음", "무지개"],
    sellMin: 60,
    sellMax: 1920,
    grades: grades([60, 240, 480, 960, 1920]),
  },
  {
    id: "pine-grosbeak",
    emoji: "🐦",
    name: "Pine Grosbeak",
    thumbnail: "/images/birds/pine_grosbeak.png",
    ko: "솔양진이",
    level: 4,
    habitat: "숲",
    rarity: "일반",
    location: "숲속 섬",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 15,
    sellMax: 480,
    grades: grades([15, 60, 120, 240, 480]),
  },
  {
    id: "golden-bowerbird",
    emoji: "🐦",
    name: "Golden Bowerbird",
    ko: "노랑머리바우어새",
    level: 4,
    habitat: "숲",
    rarity: "일반",
    location: "영혼의 참나무 숲",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 60,
    sellMax: 1920,
    grades: grades([60, 240, 480, 960, 1920]),
  },
  {
    id: "golden-fruit-dove",
    emoji: "🕊️",
    name: "Golden Fruit Dove",
    ko: "황금과일비둘기",
    level: 4,
    habitat: "꽃밭",
    rarity: "일반",
    location: "풍차 꽃밭",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 22,
    sellMax: 704,
    grades: grades([22, 90, 180, 360, 704]),
  },
  {
    id: "lady-amhersts-pheasant",
    emoji: "🐦",
    name: "Lady Amherst's Pheasant",
    thumbnail: "/images/birds/lady_amhersts_pheasant.png",
    ko: "은계",
    level: 4,
    habitat: "온천산",
    rarity: "일반",
    location: "온천산 유적",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 17,
    sellMax: 544,
    grades: grades([17, 70, 140, 280, 544]),
  },
  {
    id: "smew",
    emoji: "🦆",
    name: "Smew",
    ko: "흰비오리",
    level: 4,
    habitat: "숲",
    rarity: "일반",
    location: "숲속 호수",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 22,
    sellMax: 704,
    grades: grades([22, 90, 180, 360, 704]),
  },
  // Lv.5
  {
    id: "yellow-bellied-flycatcher",
    emoji: "🐦",
    name: "Yellow-bellied Flycatcher",
    ko: "노랑배딱새",
    level: 5,
    habitat: "어촌",
    rarity: "일반",
    location: "부두",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 15,
    sellMax: 480,
    grades: grades([15, 60, 120, 240, 480]),
  },
  {
    id: "european-bee-eater",
    emoji: "🐦",
    name: "European Bee-eater",
    ko: "유럽벌잡이새",
    level: 5,
    habitat: "온천산",
    rarity: "일반",
    location: "온천산 호숫가",
    distance: 3,
    times: ["상시"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 22,
    sellMax: 704,
    grades: grades([22, 90, 180, 352, 704]),
  },
  {
    id: "military-macaw",
    emoji: "🐦",
    name: "Military Macaw",
    ko: "초록금강앵무",
    level: 5,
    habitat: "새들의 복귀",
    rarity: "일반",
    location: "새들의 복귀 사건",
    distance: 3,
    times: ["상시"],
    weathers: ["맑음", "무지개"],
    sellMin: 15,
    sellMax: 480,
    grades: grades([15, 60, 120, 240, 480]),
  },
  {
    id: "olive-pigeon",
    emoji: "🕊️",
    name: "Olive Pigeon",
    ko: "올리브비둘기",
    level: 5,
    habitat: "온천산",
    rarity: "일반",
    location: "온천산 온천",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 27,
    sellMax: 864,
    grades: grades([27, 110, 220, 432, 864]),
  },
  {
    id: "lesser-flamingo",
    emoji: "🦩",
    name: "Lesser Flamingo",
    ko: "작은홍학",
    level: 5,
    habitat: "숲",
    rarity: "일반",
    location: "숲속 호숫가",
    distance: 4,
    times: ["상시"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 110,
    sellMax: 3520,
    grades: grades([110, 220, 440, 1760, 3520]),
  },
  {
    id: "black-tern",
    emoji: "🐦",
    name: "Black Tern",
    ko: "검정제비갈매기",
    level: 5,
    habitat: "기타",
    rarity: "일반",
    location: "구해 해변",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 22,
    sellMax: 704,
    grades: grades([22, 90, 180, 360, 704]),
  },
  // Lv.6
  {
    id: "hawfinch-lv6",
    emoji: "🐦",
    name: "Hawfinch",
    ko: "콩새",
    level: 6,
    habitat: "온천산",
    rarity: "일반",
    location: "온천산-화산 호수",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 15,
    sellMax: 480,
    grades: grades([15, 60, 120, 240, 480]),
  },
  {
    id: "golden-breasted-pigeon",
    emoji: "🕊️",
    name: "Golden-breasted Pigeon",
    ko: "황금가슴비둘기",
    level: 6,
    habitat: "어촌",
    rarity: "일반",
    location: "동쪽 부두",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 27,
    sellMax: 864,
    grades: grades([27, 110, 220, 432, 864]),
  },
  {
    id: "red-faced-cormorant",
    emoji: "🐦",
    name: "Red-faced Cormorant",
    ko: "붉은뺨가마우지",
    level: 6,
    habitat: "기타",
    rarity: "일반",
    location: "구해, 고래바다",
    distance: 4,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 22,
    sellMax: 704,
    grades: grades([22, 90, 180, 360, 704]),
  },
  {
    id: "short-eared-owl",
    emoji: "🦉",
    name: "Short-eared Owl",
    ko: "칡부엉이",
    level: 6,
    habitat: "온천산",
    rarity: "일반",
    location: "온천산 석안애",
    distance: 4,
    times: ["상시"],
    weathers: ["맑음", "무지개"],
    sellMin: 47,
    sellMax: 1504,
    grades: grades([47, 188, 376, 760, 1504]),
  },
  // Lv.7
  {
    id: "blue-tit",
    emoji: "🐦",
    name: "Blue Tit",
    ko: "푸른박새",
    level: 7,
    habitat: "꽃밭",
    rarity: "일반",
    location: "풍차 꽃밭",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 22,
    sellMax: 704,
    grades: grades([22, 90, 180, 360, 704]),
  },
  {
    id: "hyacinth-macaw-lv7",
    emoji: "🐦",
    name: "Hyacinth Macaw",
    ko: "히아신스금강앵무",
    level: 7,
    habitat: "새들의 복귀",
    rarity: "일반",
    location: "새들의 복귀 사건",
    distance: 3,
    times: ["상시"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 22,
    sellMax: 704,
    grades: grades([22, 90, 180, 360, 704]),
  },
  {
    id: "jambu-fruit-dove",
    emoji: "🕊️",
    name: "Jambu Fruit Dove",
    ko: "잠부과일비둘기",
    level: 7,
    habitat: "기타",
    rarity: "일반",
    location: "교외",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 27,
    sellMax: 864,
    grades: grades([27, 110, 220, 432, 864]),
  },
  {
    id: "common-tern",
    emoji: "🐦",
    name: "Common Tern",
    ko: "제비갈매기",
    level: 7,
    habitat: "기타",
    rarity: "일반",
    location: "동해해변",
    distance: 3,
    times: ["상시"],
    weathers: ["무지개"],
    sellMin: 35,
    sellMax: 1120,
    grades: grades([35, 140, 280, 560, 1120]),
  },
  {
    id: "common-kestrel",
    emoji: "🐦",
    name: "Common Kestrel",
    ko: "황조롱이",
    level: 7,
    habitat: "숲",
    rarity: "일반",
    location: "순록탑",
    distance: 4,
    times: ["상시"],
    weathers: ["맑음", "무지개"],
    sellMin: 47,
    sellMax: 1504,
    grades: grades([47, 190, 380, 752, 1504]),
  },
  // Lv.8
  {
    id: "eastern-bluebird",
    emoji: "🐦",
    name: "Eastern Bluebird",
    ko: "동부파랑새",
    level: 8,
    habitat: "도시",
    rarity: "일반",
    location: "도시 근교",
    distance: 3,
    times: ["상시"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 30,
    sellMax: 960,
    grades: grades([30, 120, 240, 480, 960]),
  },
  {
    id: "redpoll",
    emoji: "🐦",
    name: "redpoll",
    ko: "홍방울새",
    level: 8,
    habitat: "숲",
    rarity: "일반",
    location: "영혼의 참나무 숲",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 22,
    sellMax: 704,
    grades: grades([22, 90, 180, 360, 704]),
  },
  {
    id: "pink-pigeon",
    emoji: "🕊️",
    name: "Pink Pigeon",
    ko: "분홍비둘기",
    level: 8,
    habitat: "꽃밭",
    rarity: "일반",
    location: "꽃밭 고래산",
    distance: 3,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 27,
    sellMax: 864,
    grades: grades([27, 110, 220, 432, 864]),
  },
  {
    id: "peregrine-falcon",
    emoji: "🐦",
    name: "Peregrine Falcon",
    ko: "매",
    level: 8,
    habitat: "온천산",
    rarity: "일반",
    location: "온천산 온천",
    distance: 4,
    times: ["상시"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 65,
    sellMax: 2080,
    grades: grades([65, 260, 520, 1040, 2080]),
  },
  // Lv.9
  {
    id: "bird-of-paradise",
    emoji: "🐦",
    name: "Bird-of-paradise",
    ko: "극락풍금조",
    level: 9,
    habitat: "도시",
    rarity: "일반",
    location: "도시 근교",
    distance: 3,
    times: ["상시"],
    weathers: ["무지개"],
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "american-flamingo",
    emoji: "🦩",
    name: "American Flamingo",
    ko: "아메리카홍학",
    level: 9,
    habitat: "기타",
    rarity: "일반",
    location: "보라빛 해변",
    distance: 4,
    times: ["상시"],
    weathers: ["무지개"],
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "green-peafowl",
    emoji: "🦚",
    name: "Green Peafowl",
    ko: "녹공작",
    level: 9,
    habitat: "새들의 복귀",
    rarity: "일반",
    location: "새들의 복귀 사건",
    distance: 5,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "white-headed-duck",
    emoji: "🦆",
    name: "White-headed Duck",
    ko: "흰머리오리",
    level: 9,
    habitat: "온천산",
    rarity: "일반",
    location: "온천산 호수",
    distance: 3,
    times: ["상시"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 45,
    sellMax: 1440,
    grades: grades([45, 180, 360, 720, 1440]),
  },
  {
    id: "imperial-shag",
    emoji: "🐦",
    name: "Imperial Shag",
    ko: "황제가마우지",
    level: 9,
    habitat: "기타",
    rarity: "일반",
    location: "동해, 잔잔한바다",
    distance: 4,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 45,
    sellMax: 1440,
    grades: grades([45, 180, 360, 720, 1440]),
  },
  // Lv.10
  {
    id: "azores-bullfinch",
    emoji: "🐦",
    name: "Azores Bullfinch",
    ko: "아조레스멋쟁이새",
    level: 10,
    habitat: "어촌",
    rarity: "일반",
    location: "등대",
    distance: 3,
    times: ["상시"],
    weathers: ["무지개"],
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "fairy-bluebird",
    emoji: "🐦",
    name: "Fairy Bluebird",
    ko: "파랑딱새",
    level: 10,
    habitat: "숲",
    rarity: "일반",
    location: "숲속 점프대",
    distance: 3,
    times: ["상시"],
    weathers: ["무지개"],
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "besra",
    emoji: "🐦",
    name: "Besra",
    ko: "비둘기조롱이",
    level: 10,
    habitat: "온천산",
    rarity: "일반",
    location: "온천산 유적",
    distance: 4,
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 27,
    sellMax: 1504,
    grades: grades([27, 190, 380, 752, 1504]),
  },
  {
    id: "eurasian-eagle-owl",
    emoji: "🦉",
    name: "Eurasian Eagle-Owl",
    ko: "수리부엉이",
    level: 10,
    habitat: "숲",
    rarity: "일반",
    location: "숲속 사슴탑",
    distance: 4,
    times: ["상시"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
];
