// ── Types ─────────────────────────────────────────────────────────────────────

export type BugHabitat =
  | "도시"
  | "어촌"
  | "온천산"
  | "숲"
  | "꽃밭"
  | "물가"
  | "바닷가"
  | "초원"
  | "해안"
  | "곤충 유인"
  | "에어벌 유인장치"
  | "기타";

export interface Bug {
  id: string;
  emoji: string;
  thumbnail?: string;
  name: string;
  ko: string;
  desc?: string;
  level: number;
  weathers: string[];
  times: string[];
  location: string;
}

export interface BugGrade {
  stars: number;
  sellPrice: number;
  sellEventPrice: number;
}

export interface BugDetail extends Bug {
  habitat: BugHabitat;
  rarity: string;
  sellMin: number;
  sellMax: number;
  grades: BugGrade[];
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function grades(prices: [number, number, number, number, number]): BugGrade[] {
  return prices.map((price, i) => ({
    stars: i + 1,
    sellPrice: price,
    sellEventPrice: 0,
  }));
}

// ── Data ──────────────────────────────────────────────────────────────────────

export const BUGS: BugDetail[] = [
  // Lv.1
  {
    id: "swallowtail-butterfly",
    emoji: "🦋",
    name: "swallowtail butterfly",
    ko: "호랑나비",
    thumbnail: "/images/bugs/swallowtail_butterfly.png",
    level: 1,
    weathers: ["상시"],
    times: ["상시"],
    location: "숲",
    habitat: "숲",
    rarity: "일반",
    sellMin: 30,
    sellMax: 240,
    grades: grades([30, 45, 60, 120, 240]),
  },
  {
    id: "orange-tip",
    emoji: "🦋",
    name: "orange tip",
    ko: "유럽갈고리나비",
    thumbnail: "/images/bugs/orange_tip.png",
    level: 1,
    weathers: ["상시"],
    times: ["상시"],
    location: "도시",
    habitat: "도시",
    rarity: "일반",
    sellMin: 30,
    sellMax: 240,
    grades: grades([30, 45, 60, 120, 240]),
  },
  {
    id: "common-brimstone",
    emoji: "🦋",
    name: "common brimstone",
    thumbnail: "/images/bugs/common_brimstone.png",
    ko: "멧노랑나비",
    level: 1,
    weathers: ["상시"],
    times: ["상시"],
    location: "도시 근교",
    habitat: "도시",
    rarity: "일반",
    sellMin: 30,
    sellMax: 240,
    grades: grades([30, 45, 60, 120, 240]),
  },
  {
    id: "cabbage-white",
    emoji: "🦋",
    name: "cabbage white",
    thumbnail: "/images/bugs/cabbage_white.png",
    ko: "배추흰나비",
    level: 1,
    weathers: ["상시"],
    times: ["상시"],
    location: "어촌",
    habitat: "어촌",
    rarity: "일반",
    sellMin: 30,
    sellMax: 240,
    grades: grades([30, 45, 60, 120, 240]),
  },
  {
    id: "apollo-butterfly",
    emoji: "🦋",
    name: "apollo-butterfly",
    ko: "아폴로모시나비",
    level: 1,
    weathers: ["상시"],
    times: ["상시"],
    location: "곤충 유인",
    habitat: "곤충 유인",
    rarity: "일반",
    sellMin: 45,
    sellMax: 360,
    grades: grades([45, 67, 90, 180, 360]),
  },
  {
    id: "red-ring-swallowtail",
    emoji: "🦋",
    name: "red-ring-swallowtail",
    ko: "붉은고리호랑나비",
    level: 1,
    weathers: ["상시"],
    times: ["상시"],
    location: "곤충 유인",
    habitat: "곤충 유인",
    rarity: "일반",
    sellMin: 30,
    sellMax: 240,
    grades: grades([30, 45, 60, 120, 240]),
  },
  {
    id: "asparagus-beetle",
    emoji: "🦋",
    name: "asparagus beetle",
    ko: "아스파라거스벌레",
    thumbnail: "/images/bugs/asparagus_beetle.png",
    level: 1,
    weathers: ["상시"],
    times: ["상시"],
    location: "꽃밭",
    habitat: "꽃밭",
    rarity: "일반",
    sellMin: 55,
    sellMax: 440,
    grades: grades([55, 82, 110, 220, 440]),
  },
  {
    id: "desert-locust",
    emoji: "🦋",
    name: "desert locust",
    ko: "오아시스 메뚜기",
    thumbnail: "/images/bugs/desert_locust.png",
    level: 1,
    weathers: ["상시"],
    times: ["상시"],
    location: "온천산",
    habitat: "온천산",
    rarity: "일반",
    sellMin: 45,
    sellMax: 360,
    grades: grades([45, 67, 90, 180, 360]),
  },
  {
    id: "star-stink-bug",
    emoji: "🪲",
    name: "star-stink-bug",
    ko: "별노린재",
    level: 1,
    weathers: ["상시"],
    times: ["상시"],
    location: "집 근처 (바위)",
    habitat: "기타",
    rarity: "일반",
    sellMin: 35,
    sellMax: 280,
    grades: grades([35, 52, 70, 140, 280]),
  },
  {
    id: "scarlet-skimmer",
    emoji: "🦋",
    name: "scarlet skimmer",
    thumbnail: "/images/bugs/scarlet_skimmer.png",
    ko: "큰고추잠자리",
    level: 1,
    weathers: ["상시"],
    times: ["상시"],
    location: "물가",
    habitat: "물가",
    rarity: "일반",
    sellMin: 35,
    sellMax: 280,
    grades: grades([35, 52, 70, 140, 280]),
  },
  {
    id: "sulkowskyi-morpho",
    emoji: "🦋",
    name: "sulkowskyi-morpho",
    ko: "슬코스키몰포나비",
    level: 1,
    weathers: ["상시"],
    times: ["상시"],
    location: "에어벌 유인장치",
    habitat: "에어벌 유인장치",
    rarity: "일반",
    sellMin: 90,
    sellMax: 720,
    grades: grades([90, 135, 180, 360, 720]),
  },
  // Lv.2
  {
    id: "small-blue-butterfly",
    emoji: "🦋",
    name: "small-blue-butterfly",
    ko: "연푸른부전나비",
    level: 2,
    weathers: ["상시"],
    times: ["상시"],
    location: "도시",
    habitat: "도시",
    rarity: "일반",
    sellMin: 105,
    sellMax: 840,
    grades: grades([105, 157, 210, 420, 840]),
  },
  {
    id: "green-tiger-beetle",
    emoji: "🪲",
    name: "green-tiger-beetle",
    ko: "녹색호랑풍뎅이",
    level: 2,
    weathers: ["상시"],
    times: ["상시"],
    location: "온천산",
    habitat: "온천산",
    rarity: "일반",
    sellMin: 110,
    sellMax: 880,
    grades: grades([110, 165, 220, 440, 880]),
  },
  {
    id: "wasp-longhorn-beetle",
    emoji: "🪲",
    name: "wasp-longhorn-beetle",
    ko: "말벌호랑하늘소",
    level: 2,
    weathers: ["상시"],
    times: ["상시"],
    location: "숲 (꽃밭)",
    habitat: "숲",
    rarity: "일반",
    sellMin: 110,
    sellMax: 880,
    grades: grades([110, 165, 220, 440, 880]),
  },
  {
    id: "blue-flower-chafer",
    emoji: "🪲",
    name: "blue-flower-chafer",
    ko: "파란꽃풍뎅이",
    level: 2,
    weathers: ["비", "눈", "무지개"],
    times: ["상시"],
    location: "집 근처 (바위)",
    habitat: "기타",
    rarity: "일반",
    sellMin: 165,
    sellMax: 1320,
    grades: grades([165, 247, 330, 660, 1320]),
  },
  {
    id: "club-legged-grasshopper",
    emoji: "🦋",
    name: "club-legged-grasshopper",
    ko: "망치다리메뚜기",
    level: 2,
    weathers: ["상시"],
    times: ["상시"],
    location: "어촌 (꽃밭, 관목)",
    habitat: "어촌",
    rarity: "일반",
    sellMin: 45,
    sellMax: 360,
    grades: grades([45, 67, 90, 180, 360]),
  },
  {
    id: "seven-spot-ladybird",
    emoji: "🐞",
    name: "seven spot ladybird",
    ko: "칠성 무당벌레",
    thumbnail: "/images/bugs/seven_spot_ladybird.png",
    level: 2,
    weathers: ["비", "눈", "무지개"],
    times: ["상시"],
    location: "도시 근교",
    habitat: "도시",
    rarity: "일반",
    sellMin: 110,
    sellMax: 880,
    grades: grades([110, 165, 220, 440, 880]),
  },
  {
    id: "four-spotted-chaser",
    emoji: "🦋",
    name: "four-spotted-chaser",
    ko: "넉점박이잠자리",
    level: 2,
    weathers: ["비", "눈", "무지개"],
    times: ["상시"],
    location: "도시 근교 호수",
    habitat: "도시",
    rarity: "일반",
    sellMin: 75,
    sellMax: 600,
    grades: grades([75, 112, 150, 300, 600]),
  },
  {
    id: "bumblebee",
    emoji: "🐝",
    name: "bumblebee",
    ko: "호박벌",
    thumbnail: "/images/bugs/bumblebee.png",
    level: 2,
    weathers: ["상시"],
    times: ["상시"],
    location: "꽃밭",
    habitat: "꽃밭",
    rarity: "일반",
    sellMin: 110,
    sellMax: 880,
    grades: grades([110, 165, 220, 440, 880]),
  },
  // Lv.3
  {
    id: "purple-emperor",
    emoji: "🦋",
    name: "purple-emperor",
    ko: "보라네발나비",
    level: 3,
    weathers: ["맑음", "무지개"],
    times: ["새벽", "낮", "밤"],
    location: "고래산 꽃밭",
    habitat: "꽃밭",
    rarity: "일반",
    sellMin: 90,
    sellMax: 720,
    grades: grades([90, 135, 180, 360, 720]),
  },
  {
    id: "red-necked-swallow-moth",
    emoji: "🦋",
    name: "red-necked-swallow-moth",
    ko: "붉은목제비나비",
    level: 3,
    weathers: ["상시"],
    times: ["새벽", "아침", "밤"],
    location: "집 근처 (관목, 땅)",
    habitat: "기타",
    rarity: "일반",
    sellMin: 90,
    sellMax: 720,
    grades: grades([90, 135, 180, 360, 720]),
  },
  {
    id: "moon-moth",
    emoji: "🦋",
    name: "moon-moth",
    ko: "긴꼬리산누에나방",
    level: 3,
    weathers: ["맑음", "무지개"],
    times: ["아침", "낮", "밤"],
    location: "도시 근교",
    habitat: "도시",
    rarity: "일반",
    sellMin: 105,
    sellMax: 840,
    grades: grades([105, 157, 210, 420, 840]),
  },
  {
    id: "pyrochroid-beetle",
    emoji: "🪲",
    name: "pyrochroid-beetle",
    ko: "홍날개",
    thumbnail: "/images/bugs/pyrochroid_beetle.png",
    level: 3,
    weathers: ["상시"],
    times: ["상시"],
    location: "온천 산 온천 (바위, 땅)",
    habitat: "온천산",
    rarity: "일반",
    sellMin: 110,
    sellMax: 880,
    grades: grades([110, 165, 220, 440, 880]),
  },
  {
    id: "pink-katydid",
    emoji: "🦋",
    name: "pink katydid",
    ko: "분홍색 철써기",
    thumbnail: "/images/bugs/pink_katydid.png",
    level: 3,
    weathers: ["상시"],
    times: ["상시"],
    location: "곤충 유인",
    habitat: "곤충 유인",
    rarity: "일반",
    sellMin: 90,
    sellMax: 720,
    grades: grades([90, 135, 180, 360, 720]),
  },
  {
    id: "katydid",
    emoji: "🦋",
    name: "katydid",
    ko: "여치",
    level: 3,
    weathers: ["상시"],
    times: ["상시"],
    location: "보라빛해변 꽃밭",
    habitat: "꽃밭",
    rarity: "일반",
    sellMin: 180,
    sellMax: 1440,
    grades: grades([180, 270, 360, 720, 1440]),
  },
  {
    id: "white-tailed-bumblebee",
    emoji: "🐝",
    name: "white-tailed-bumblebee",
    ko: "흰점꼬리털벌",
    thumbnail: "/images/bugs/white-tailed-bumblebee.png",
    level: 3,
    weathers: ["상시"],
    times: ["아침", "낮", "밤"],
    location: "숲-순록탑",
    habitat: "숲",
    rarity: "일반",
    sellMin: 165,
    sellMax: 1320,
    grades: grades([165, 247, 330, 660, 1320]),
  },
  {
    id: "ant",
    emoji: "🐜",
    name: "ant",
    ko: "개미",
    level: 3,
    weathers: ["상시"],
    times: ["상시"],
    location: "어촌 광장",
    habitat: "어촌",
    rarity: "일반",
    sellMin: 220,
    sellMax: 1760,
    grades: grades([220, 330, 440, 880, 1760]),
  },
  // Lv.4
  {
    id: "leopard-butterfly",
    emoji: "🦋",
    name: "leopard-butterfly",
    ko: "표범무늬네발나비",
    level: 4,
    weathers: ["비", "눈", "무지개"],
    times: ["새벽", "아침", "밤"],
    location: "어촌 부두",
    habitat: "어촌",
    rarity: "일반",
    sellMin: 90,
    sellMax: 720,
    grades: grades([90, 135, 180, 360, 720]),
  },
  {
    id: "striped-grasshopper",
    emoji: "🦋",
    name: "striped-grasshopper",
    ko: "큰줄무늬메뚜기",
    level: 4,
    weathers: ["맑음", "무지개"],
    times: ["새벽", "낮", "밤"],
    location: "도시 근교",
    habitat: "도시",
    rarity: "일반",
    sellMin: 140,
    sellMax: 1120,
    grades: grades([140, 210, 280, 560, 1120]),
  },
  {
    id: "four-spot-ladybird",
    emoji: "🐞",
    name: "four spot ladybird",
    ko: "사성 무당벌레",
    thumbnail: "/images/bugs/four_spot_ladybird.png",
    level: 4,
    weathers: ["비", "눈", "무지개"],
    times: ["상시"],
    location: "온천산 화산호",
    habitat: "온천산",
    rarity: "일반",
    sellMin: 165,
    sellMax: 1320,
    grades: grades([165, 247, 330, 660, 1320]),
  },
  {
    id: "cicada",
    emoji: "🦋",
    name: "cicada",
    ko: "매미",
    thumbnail: "/images/bugs/cicada.png",
    level: 4,
    weathers: ["상시"],
    times: ["새벽", "낮", "밤"],
    location: "숲-이상한대나무숲",
    habitat: "숲",
    rarity: "일반",
    sellMin: 220,
    sellMax: 1760,
    grades: grades([220, 330, 440, 880, 1760]),
  },
  {
    id: "broad-bodied-chaser",
    emoji: "🦋",
    name: "broad-bodied-chaser",
    ko: "밀잠자리",
    level: 4,
    weathers: ["비", "눈", "무지개"],
    times: ["상시"],
    location: "강가",
    habitat: "물가",
    rarity: "일반",
    sellMin: 75,
    sellMax: 600,
    grades: grades([75, 112, 150, 300, 600]),
  },
  {
    id: "rainbow-mantis",
    emoji: "🦋",
    name: "rainbow-mantis",
    ko: "무지개사마귀",
    level: 4,
    weathers: ["맑음", "무지개"],
    times: ["새벽", "낮", "밤"],
    location: "온천산 (절벽, 꽃밭)",
    habitat: "온천산",
    rarity: "일반",
    sellMin: 195,
    sellMax: 1560,
    grades: grades([195, 292, 390, 780, 1560]),
  },
  // Lv.5
  {
    id: "alpine-longhorn-beetle",
    emoji: "🪲",
    name: "alpine-longhorn-beetle",
    ko: "고산수염하늘소",
    level: 5,
    weathers: ["무지개"],
    times: ["상시"],
    location: "숲-숲속섬",
    habitat: "숲",
    rarity: "일반",
    sellMin: 165,
    sellMax: 1320,
    grades: grades([165, 247, 330, 660, 1320]),
  },
  {
    id: "papua-mantis",
    emoji: "🦋",
    name: "papua-mantis",
    ko: "파푸아사마귀",
    level: 5,
    weathers: ["맑음", "무지개"],
    times: ["상시"],
    location: "온천산 (유적, 꽃밭, 풀)",
    habitat: "온천산",
    rarity: "일반",
    sellMin: 390,
    sellMax: 3120,
    grades: grades([390, 585, 780, 1560, 3120]),
  },
  {
    id: "peacock-butterfly",
    emoji: "🦋",
    name: "peacock-butterfly",
    ko: "공작나비",
    level: 5,
    weathers: ["상시"],
    times: ["상시"],
    location: "풍차 꽃밭",
    habitat: "꽃밭",
    rarity: "일반",
    sellMin: 90,
    sellMax: 720,
    grades: grades([90, 135, 180, 360, 720]),
  },
  {
    id: "comma-butterfly",
    emoji: "🦋",
    name: "comma-butterfly",
    ko: "신선나비",
    level: 5,
    weathers: ["맑음", "무지개"],
    times: ["새벽", "아침", "낮"],
    location: "온천산 (온천)",
    habitat: "온천산",
    rarity: "일반",
    sellMin: 90,
    sellMax: 720,
    grades: grades([90, 135, 180, 360, 720]),
  },
  {
    id: "white-witch-moth",
    emoji: "🦋",
    name: "white-witch-moth",
    ko: "흰마녀밤나방",
    level: 5,
    weathers: ["맑음", "무지개"],
    times: ["상시"],
    location: "곤충 유인",
    habitat: "곤충 유인",
    rarity: "일반",
    sellMin: 90,
    sellMax: 720,
    grades: grades([90, 135, 180, 360, 720]),
  },
  {
    id: "harlequin-ladybird",
    emoji: "🐞",
    name: "harlequin-ladybird",
    ko: "이색무당벌레",
    level: 5,
    weathers: ["비", "눈", "무지개"],
    times: ["새벽", "낮", "밤"],
    location: "숲-순록탑 (꽃, 땅)",
    habitat: "숲",
    rarity: "일반",
    sellMin: 165,
    sellMax: 1320,
    grades: grades([165, 247, 330, 660, 1320]),
  },
  {
    id: "purple-bee",
    emoji: "🐝",
    name: "purple bee",
    ko: "보라벌",
    thumbnail: "/images/bugs/purple_bee.png",
    level: 5,
    weathers: ["맑음", "무지개"],
    times: ["상시"],
    location: "고래산 (큰 나무, 관목)",
    habitat: "숲",
    rarity: "일반",
    sellMin: 165,
    sellMax: 1320,
    grades: grades([165, 247, 330, 660, 1320]),
  },
  // Lv.6
  {
    id: "green-banded-swallowtail",
    emoji: "🦋",
    name: "green-banded-swallowtail",
    ko: "녹색날개호랑나비",
    level: 6,
    weathers: ["상시"],
    times: ["새벽", "밤"],
    location: "도시 근교",
    habitat: "도시",
    rarity: "일반",
    sellMin: 150,
    sellMax: 1200,
    grades: grades([150, 225, 300, 600, 1200]),
  },
  {
    id: "alpine-stag-beetle",
    emoji: "🪲",
    name: "alpine-stag-beetle",
    ko: "산악사슴벌레",
    level: 6,
    weathers: ["비", "눈", "무지개"],
    times: ["아침", "낮", "밤"],
    location: "숲 점프 스테이지",
    habitat: "숲",
    rarity: "일반",
    sellMin: 275,
    sellMax: 2200,
    grades: grades([275, 412, 550, 1100, 2200]),
  },
  {
    id: "silver-jewel-beetle",
    emoji: "🪲",
    name: "silver-jewel-beetle",
    ko: "은빛보석풍뎅이",
    level: 6,
    weathers: ["맑음", "무지개"],
    times: ["새벽", "아침", "낮"],
    location: "온천산 절벽",
    habitat: "온천산",
    rarity: "일반",
    sellMin: 165,
    sellMax: 1320,
    grades: grades([165, 247, 330, 660, 1320]),
  },
  {
    id: "blue-shield-bug",
    emoji: "🪲",
    name: "blue-shield-bug",
    ko: "파란노린재",
    level: 6,
    weathers: ["상시"],
    times: ["아침", "낮"],
    location: "어촌 등대 (풀)",
    habitat: "어촌",
    rarity: "일반",
    sellMin: 110,
    sellMax: 880,
    grades: grades([110, 165, 220, 440, 880]),
  },
  {
    id: "demoiselle",
    emoji: "🦋",
    name: "demoiselle",
    ko: "물잠자리",
    level: 6,
    weathers: ["비", "눈", "무지개"],
    times: ["상시"],
    location: "숲-숲속 호수",
    habitat: "숲",
    rarity: "일반",
    sellMin: 110,
    sellMax: 880,
    grades: grades([110, 165, 220, 440, 880]),
  },
  // Lv.7
  {
    id: "menelaus-blue-morpho",
    emoji: "🦋",
    name: "menelaus-blue-morpho",
    ko: "메넬라우스나비",
    level: 7,
    weathers: ["맑음", "무지개"],
    times: ["아침", "낮", "밤"],
    location: "숲-영혼의 참나무 숲",
    habitat: "숲",
    rarity: "일반",
    sellMin: 150,
    sellMax: 1200,
    grades: grades([150, 225, 300, 600, 1200]),
  },
  {
    id: "monarch-butterfly",
    emoji: "🦋",
    name: "monarch-butterfly",
    ko: "왕나비",
    level: 7,
    weathers: ["비", "눈", "무지개"],
    times: ["상시"],
    location: "곤충 유인",
    habitat: "곤충 유인",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "typhon-dung-beetle",
    emoji: "🪲",
    name: "typhon-dung-beetle",
    ko: "티폰쇠똥구리",
    level: 7,
    weathers: ["상시"],
    times: ["새벽", "아침", "낮"],
    location: "온천산 (유적, 절벽, 땅)",
    habitat: "온천산",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "jewel-flower-beetle",
    emoji: "🪲",
    name: "jewel-flower-beetle",
    ko: "보석꽃풍뎅이",
    level: 7,
    weathers: ["비", "눈", "무지개"],
    times: ["아침", "낮"],
    location: "고래산 꽃밭",
    habitat: "꽃밭",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "golden-jewel-beetle",
    emoji: "🪲",
    name: "golden-jewel-beetle",
    ko: "황금보석풍뎅이",
    level: 7,
    weathers: ["맑음", "무지개"],
    times: ["낮", "밤"],
    location: "숲-점핑플랫폼",
    habitat: "숲",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "rose-darter",
    emoji: "🦋",
    name: "rose-darter",
    ko: "찔레잠자리",
    level: 7,
    weathers: ["무지개"],
    times: ["새벽", "낮", "밤"],
    location: "온천산 호수",
    habitat: "온천산",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  // Lv.8
  {
    id: "isabella-moth",
    emoji: "🦋",
    name: "isabella-moth",
    ko: "이사벨라나방",
    level: 8,
    weathers: ["맑음", "무지개"],
    times: ["낮", "밤"],
    location: "숲-이상한대나무숲",
    habitat: "숲",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "comet-moth",
    emoji: "🦋",
    name: "comet-moth",
    ko: "혜성꼬리나방",
    level: 8,
    weathers: ["맑음", "무지개"],
    times: ["새벽", "밤"],
    location: "도시 근교 (가로등)",
    habitat: "도시",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "rhinoceros-beetle",
    emoji: "🪲",
    name: "rhinoceros-beetle",
    ko: "장수풍뎅이",
    level: 8,
    weathers: ["맑음", "무지개"],
    times: ["새벽", "밤"],
    location: "어촌-동쪽 부두",
    habitat: "어촌",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "picasso-bug",
    emoji: "🪲",
    name: "picasso-bug",
    ko: "피카소노린재",
    level: 8,
    weathers: ["맑음", "무지개"],
    times: ["새벽", "낮", "밤"],
    location: "보라빛해변 꽃밭",
    habitat: "꽃밭",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  // Lv.9
  {
    id: "golden-stag-beetle",
    emoji: "🪲",
    name: "golden-stag-beetle",
    ko: "황금사슴벌레",
    level: 9,
    weathers: [],
    times: [],
    location: "-",
    habitat: "기타",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "pearl-butterfly",
    emoji: "🦋",
    name: "pearl-butterfly",
    ko: "진주네발나비",
    level: 9,
    weathers: ["비", "눈", "무지개"],
    times: ["새벽", "아침"],
    location: "풍차 꽃밭",
    habitat: "꽃밭",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "golden-ghost-stag-beetle",
    emoji: "🪲",
    name: "golden-ghost-stag-beetle",
    ko: "황금귀신사슴벌레",
    level: 9,
    weathers: ["비", "눈", "무지개"],
    times: ["새벽", "밤"],
    location: "숲-영혼의 참나무",
    habitat: "숲",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "rainbow-stag-beetle",
    emoji: "🪲",
    name: "rainbow-stag-beetle",
    ko: "무지개사슴벌레",
    level: 9,
    weathers: ["상시"],
    times: ["상시"],
    location: "곤충 유인 (유적, 나무)",
    habitat: "곤충 유인",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "devil-flower-mantis",
    emoji: "🦋",
    name: "devil-flower-mantis",
    ko: "악마꽃사마귀",
    level: 9,
    weathers: ["비", "눈", "무지개"],
    times: ["낮", "밤"],
    location: "온천산 (유적, 꽃, 땅)",
    habitat: "온천산",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "blue-bumblebee",
    emoji: "🐝",
    name: "blue-bumblebee",
    ko: "파란호박벌",
    level: 9,
    weathers: ["무지개"],
    times: ["새벽", "낮", "밤"],
    location: "어촌 광장",
    habitat: "어촌",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  // Lv.10
  {
    id: "helena-morpho",
    emoji: "🦋",
    name: "helena-morpho",
    ko: "헬레나모르포",
    level: 10,
    weathers: ["무지개"],
    times: ["아침", "낮"],
    location: "보라빛해변 꽃밭",
    habitat: "꽃밭",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "hecuba-morpho",
    emoji: "🦋",
    name: "hecuba-morpho",
    ko: "헤쿠바몰포나비",
    level: 10,
    weathers: ["무지개"],
    times: ["아침", "낮"],
    location: "숲-순록탑",
    habitat: "숲",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "hercules-beetle",
    emoji: "🪲",
    name: "hercules-beetle",
    ko: "헤라클레스풍뎅이",
    level: 10,
    weathers: ["맑음", "무지개"],
    times: ["낮", "밤"],
    location: "화산호",
    habitat: "온천산",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
  {
    id: "spiral-bagworm-moth",
    emoji: "🦋",
    name: "spiral-bagworm-moth",
    ko: "나선주머니나방",
    level: 10,
    weathers: ["맑음", "무지개"],
    times: ["새벽", "밤"],
    location: "숲-순록탑 (나뭇가지)",
    habitat: "숲",
    rarity: "일반",
    sellMin: 0,
    sellMax: 0,
    grades: grades([0, 0, 0, 0, 0]),
  },
];
