// ── Types ─────────────────────────────────────────────────────────────────────

export type FishType = "강" | "호수" | "바다";

export interface Fish {
  id: string;
  emoji: string;
  thumbnail?: string;
  name: string;
  ko: string;
  desc?: string;
  level: number;
  weathers: string[];
  times: string[];
  location: string;
}

export interface FishGrade {
  stars: number;
  sellPrice: number;
  sellEventPrice: number;
}

export interface FishDetail extends Fish {
  fishType: FishType;
  shadowSize: string;
  sellMin: number;
  sellMax: number;
  grades: FishGrade[];
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function grades(prices: [number, number, number, number, number]): FishGrade[] {
  return prices.map((price, i) => ({
    stars: i + 1,
    sellPrice: price,
    sellEventPrice: 0,
  }));
}

// ── Data ──────────────────────────────────────────────────────────────────────

export const FISHES: FishDetail[] = [
  // Lv.1 - 강
  {
    id: "freshwater-bass",
    emoji: "🐟",
    // thumbnail: "/images/fishes/freshwater-bass.png",
    name: "Freshwater Bass",
    ko: "민물배스",
    level: 1,
    fishType: "강",
    shadowSize: "중형",
    location: "모든 강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 75,
    sellMax: 600,
    grades: grades([75, 112, 150, 300, 600]),
  },
  {
    id: "sky-loach",
    emoji: "🐟",
    thumbnail: "/images/fishes/sky_loach.png",
    name: "Sky Loach",
    ko: "하늘종개",
    level: 1,
    fishType: "강",
    shadowSize: "소형",
    location: "거목강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "barbel",
    emoji: "🐟",
    // thumbnail: "/images/fishes/barbel.png",
    name: "Barbel",
    ko: "바벨",
    level: 1,
    fishType: "강",
    shadowSize: "중형",
    location: "얕은 강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 75,
    sellMax: 600,
    grades: grades([75, 112, 150, 300, 600]),
  },
  {
    id: "largemouth-bass",
    emoji: "🐟",
    // thumbnail: "/images/fishes/largemouth-bass.png",
    name: "Largemouth Bass",
    ko: "큰얼룩배스",
    level: 1,
    fishType: "강",
    shadowSize: "소형",
    location: "노을강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "minnow",
    emoji: "🐟",
    // thumbnail: "/images/fishes/minnow.png",
    name: "Minnow",
    ko: "미노우",
    level: 1,
    fishType: "강",
    shadowSize: "소형",
    location: "고요한 강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "giant-shrimp",
    emoji: "🦐",
    // thumbnail: "/images/fishes/giant-shrimp.png",
    name: "Giant Shrimp",
    ko: "왕새우",
    level: 1,
    fishType: "강",
    shadowSize: "소형",
    location: "모든 강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },

  // Lv.1 - 호수
  {
    id: "european-frog",
    emoji: "🐸",
    // thumbnail: "/images/fishes/european-frog.png",
    name: "European Frog",
    ko: "유럽참개구리",
    level: 1,
    fishType: "호수",
    shadowSize: "파랑",
    location: "모든 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 320,
    sellMax: 2560,
    grades: grades([320, 480, 640, 1280, 2560]),
  },
  {
    id: "european-chub",
    emoji: "🐟",
    // thumbnail: "/images/fishes/european-chub.png",
    name: "European Chub",
    ko: "유럽처브",
    level: 1,
    fishType: "호수",
    shadowSize: "중형",
    location: "모든 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 75,
    sellMax: 600,
    grades: grades([75, 112, 150, 300, 600]),
  },
  {
    id: "tench",
    emoji: "🐟",
    // thumbnail: "/images/fishes/tench.png",
    name: "Tench",
    ko: "텐치",
    level: 1,
    fishType: "호수",
    shadowSize: "소형",
    location: "숲속 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "arctic-salmon",
    emoji: "🐟",
    // thumbnail: "/images/fishes/arctic-salmon.png",
    name: "Arctic Salmon",
    ko: "극지연어",
    level: 1,
    fishType: "호수",
    shadowSize: "중형",
    location: "온천 산수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 105,
    sellMax: 840,
    grades: grades([105, 157, 210, 420, 840]),
  },
  {
    id: "crucian-carp",
    emoji: "🐟",
    // thumbnail: "/images/fishes/crucian-carp.png",
    name: "Crucian Carp",
    ko: "붕어",
    level: 1,
    fishType: "호수",
    shadowSize: "중형",
    location: "근교 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 75,
    sellMax: 600,
    grades: grades([75, 112, 150, 300, 600]),
  },
  {
    id: "european-bleak",
    emoji: "🐟",
    // thumbnail: "/images/fishes/european-bleak.png",
    name: "European Bleak",
    ko: "유럽백조어",
    level: 1,
    fishType: "호수",
    shadowSize: "소형",
    location: "모든 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "bleak",
    emoji: "🐟",
    // thumbnail: "/images/fishes/bleak.png",
    name: "Bleak",
    ko: "백조어",
    level: 1,
    fishType: "호수",
    shadowSize: "소형",
    location: "근교 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },

  // Lv.1 - 바다
  {
    id: "sea-bass",
    emoji: "🐟",
    thumbnail: "/images/fishes/sea_bass.png",
    name: "Sea Bass",
    ko: "배스",
    level: 1,
    fishType: "바다",
    shadowSize: "중형",
    location: "모든 바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 75,
    sellMax: 600,
    grades: grades([75, 112, 150, 300, 600]),
  },
  {
    id: "skipjack-tuna",
    emoji: "🐟",
    // thumbnail: "/images/fishes/skipjack-tuna.png",
    name: "Skipjack Tuna",
    ko: "가다랑어",
    level: 1,
    fishType: "바다",
    shadowSize: "대형",
    location: "모든 바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 210,
    sellMax: 1680,
    grades: grades([210, 315, 420, 840, 1680]),
  },
  {
    id: "hairtail",
    emoji: "🐟",
    // thumbnail: "/images/fishes/hairtail.png",
    name: "Hairtail",
    ko: "갈치",
    level: 1,
    fishType: "바다",
    shadowSize: "대형",
    location: "잔잔한 바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 105,
    sellMax: 840,
    grades: grades([105, 157, 210, 420, 840]),
  },
  {
    id: "sea-shrimp",
    emoji: "🦐",
    // thumbnail: "/images/fishes/sea-shrimp.png",
    name: "Sea Shrimp",
    ko: "바다새우",
    level: 1,
    fishType: "바다",
    shadowSize: "소형",
    location: "동해",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "horse-mackerel",
    emoji: "🐟",
    // thumbnail: "/images/fishes/horse-mackerel.png",
    name: "Horse Mackerel",
    ko: "전갱이",
    level: 1,
    fishType: "바다",
    shadowSize: "소형",
    location: "고래바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },

  // Lv.2 - 호수
  {
    id: "stone-minnow",
    emoji: "🐟",
    // thumbnail: "/images/fishes/stone-minnow.png",
    name: "Stone Minnow",
    ko: "돌마자",
    level: 2,
    fishType: "호수",
    shadowSize: "소형",
    location: "근교 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },
  {
    id: "mud-sunfish",
    emoji: "🐟",
    // thumbnail: "/images/fishes/mud-sunfish.png",
    name: "Mud Sunfish",
    ko: "머드개복치",
    level: 2,
    fishType: "호수",
    shadowSize: "소형",
    location: "숲속 호수",
    times: ["아침", "낮", "밤"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },
  {
    id: "sea-smelt",
    emoji: "🐟",
    // thumbnail: "/images/fishes/sea-smelt.png",
    name: "Sea Smelt",
    ko: "바다빙어",
    level: 2,
    fishType: "호수",
    shadowSize: "소형",
    location: "초원 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },
  {
    id: "plum-bass",
    emoji: "🐟",
    // thumbnail: "/images/fishes/plum-bass.png",
    name: "Plum Bass",
    ko: "매화농어",
    level: 2,
    fishType: "호수",
    shadowSize: "소형",
    location: "온천 산수",
    times: ["낮", "밤"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },

  // Lv.2 - 바다
  {
    id: "atlantic-silver-shark",
    emoji: "🦈",
    // thumbnail: "/images/fishes/atlantic-silver-shark.png",
    name: "Atlantic Silver Shark",
    ko: "대서양은상어",
    level: 2,
    fishType: "바다",
    shadowSize: "소형",
    location: "모든 바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 320,
    sellMax: 2560,
    grades: grades([320, 480, 640, 1280, 2560]),
  },
  {
    id: "sea-stickleback",
    emoji: "🐟",
    // thumbnail: "/images/fishes/sea-stickleback.png",
    name: "Sea Stickleback",
    ko: "바다가시고기",
    level: 2,
    fishType: "바다",
    shadowSize: "소형",
    location: "구해",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "yellow-goatfish",
    emoji: "🐟",
    // thumbnail: "/images/fishes/yellow-goatfish.png",
    name: "Yellow Goatfish",
    ko: "노랑촉수",
    level: 2,
    fishType: "바다",
    shadowSize: "금색",
    location: "바다낚시",
    times: ["상시"],
    weathers: ["무지개"],
    sellMin: 320,
    sellMax: 2560,
    grades: grades([320, 480, 640, 1280, 2560]),
  },

  // Lv.3 - 강
  {
    id: "freshwater-zander",
    emoji: "🐟",
    // thumbnail: "/images/fishes/freshwater-zander.png",
    name: "Freshwater Zander",
    ko: "민물잰더",
    level: 3,
    fishType: "강",
    shadowSize: "중형",
    location: "거목강",
    times: ["상시"],
    weathers: ["맑음", "무지개"],
    sellMin: 230,
    sellMax: 1840,
    grades: grades([230, 345, 460, 920, 1840]),
  },

  // Lv.3 - 호수
  {
    id: "mussel",
    emoji: "🐚",
    thumbnail: "/images/fishes/mussel.png",
    name: "Mussel",
    ko: "홍합",
    level: 3,
    fishType: "호수",
    shadowSize: "소형",
    location: "근교 호수",
    times: ["상시"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },
  {
    id: "tadpole",
    emoji: "🐸",
    // thumbnail: "/images/fishes/tadpole.png",
    name: "Tadpole",
    ko: "올챙이",
    level: 3,
    fishType: "호수",
    shadowSize: "소형",
    location: "온천 산수",
    times: ["상시"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },
  {
    id: "european-crayfish",
    emoji: "🦞",
    // thumbnail: "/images/fishes/european-crayfish.png",
    name: "European Crayfish",
    ko: "유럽민물가재",
    level: 3,
    fishType: "호수",
    shadowSize: "중형",
    location: "숲속 호수",
    times: ["새벽", "아침", "밤"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },

  // Lv.3 - 바다
  {
    id: "yellow-scad",
    emoji: "🐟",
    // thumbnail: "/images/fishes/yellow-scad.png",
    name: "Yellow Scad",
    ko: "노란전갱이",
    level: 3,
    fishType: "바다",
    shadowSize: "중형",
    location: "잔잔한 바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 155,
    sellMax: 1240,
    grades: grades([155, 232, 310, 620, 1240]),
  },
  {
    id: "seahorse",
    emoji: "🐟",
    thumbnail: "/images/fishes/seahorse.png",
    name: "Seahorse",
    ko: "해마",
    level: 3,
    fishType: "바다",
    shadowSize: "소형",
    location: "고래바다",
    times: ["새벽", "아침", "낮"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },
  {
    id: "monkfish",
    emoji: "🐟",
    // thumbnail: "/images/fishes/monkfish.png",
    name: "Monkfish",
    ko: "아귀",
    level: 3,
    fishType: "바다",
    shadowSize: "금색",
    location: "바다낚시",
    times: ["상시"],
    weathers: ["무지개"],
    sellMin: 320,
    sellMax: 2560,
    grades: grades([320, 480, 640, 1280, 2560]),
  },
  {
    id: "hermit-crab",
    emoji: "🦀",
    // thumbnail: "/images/fishes/hermit-crab.png",
    name: "Hermit Crab",
    ko: "소라게",
    level: 3,
    fishType: "바다",
    shadowSize: "소형",
    location: "동해",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },
  {
    id: "clownfish",
    emoji: "🐟",
    thumbnail: "/images/fishes/clownfish.png",
    name: "Clownfish",
    ko: "흰동가리",
    level: 3,
    fishType: "바다",
    shadowSize: "소형",
    location: "구해",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },

  // Lv.4 - 강
  {
    id: "european-carp",
    emoji: "🐟",
    // thumbnail: "/images/fishes/european-carp.png",
    name: "European Carp",
    ko: "유럽잉어",
    level: 4,
    fishType: "강",
    shadowSize: "중형",
    location: "노을강",
    times: ["낮", "밤"],
    weathers: ["맑음", "무지개"],
    sellMin: 230,
    sellMax: 1840,
    grades: grades([230, 345, 460, 920, 1840]),
  },
  {
    id: "freshwater-cod",
    emoji: "🐟",
    // thumbnail: "/images/fishes/freshwater-cod.png",
    name: "Freshwater Cod",
    ko: "민물대구",
    level: 4,
    fishType: "강",
    shadowSize: "중형",
    location: "고요한 강",
    times: ["낮", "밤"],
    weathers: ["상시"],
    sellMin: 230,
    sellMax: 1840,
    grades: grades([230, 345, 460, 920, 1840]),
  },
  {
    id: "piranha",
    emoji: "🐟",
    // thumbnail: "/images/fishes/piranha.png",
    name: "Piranha",
    ko: "레드밸리피라냐",
    level: 4,
    fishType: "강",
    shadowSize: "중형",
    location: "거목강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 230,
    sellMax: 1840,
    grades: grades([230, 345, 460, 920, 1840]),
  },

  // Lv.4 - 호수
  {
    id: "bigmouth-bass",
    emoji: "🐟",
    thumbnail: "/images/fishes/bigmouth_bass.png",
    name: "Bigmouth Bass",
    ko: "큰입배스",
    level: 4,
    fishType: "호수",
    shadowSize: "중형",
    location: "숲속 호수",
    times: ["상시"],
    weathers: ["맑음", "무지개"],
    sellMin: 230,
    sellMax: 1840,
    grades: grades([230, 345, 460, 920, 1840]),
  },
  {
    id: "freshwater-crab",
    emoji: "🦀",
    // thumbnail: "/images/fishes/freshwater-crab.png",
    name: "Freshwater Crab",
    ko: "민물게",
    level: 4,
    fishType: "호수",
    shadowSize: "소형",
    location: "근교 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },
  {
    id: "butterfly-carp",
    emoji: "🐟",
    // thumbnail: "/images/fishes/butterfly-carp.png",
    name: "Butterfly Carp",
    ko: "나비잉어",
    level: 4,
    fishType: "호수",
    shadowSize: "대형",
    location: "초원 호수",
    times: ["상시"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 320,
    sellMax: 2560,
    grades: grades([320, 480, 640, 1280, 2560]),
  },

  // Lv.4 - 바다
  {
    id: "goby",
    emoji: "🐟",
    // thumbnail: "/images/fishes/goby.png",
    name: "Goby",
    ko: "망둥어",
    level: 4,
    fishType: "바다",
    shadowSize: "소형",
    location: "동해",
    times: ["아침", "낮"],
    weathers: ["상시"],
    sellMin: 150,
    sellMax: 1200,
    grades: grades([150, 225, 300, 600, 1200]),
  },
  {
    id: "common-octopus",
    emoji: "🐙",
    // thumbnail: "/images/fishes/common-octopus.png",
    name: "Common Octopus",
    ko: "참문어",
    level: 4,
    fishType: "바다",
    shadowSize: "금색",
    location: "바다낚시",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 320,
    sellMax: 2560,
    grades: grades([320, 480, 640, 1280, 2560]),
  },
  {
    id: "atlantic-salmon",
    emoji: "🐟",
    // thumbnail: "/images/fishes/atlantic-salmon.png",
    name: "Atlantic Salmon",
    ko: "대서양연어",
    level: 4,
    fishType: "바다",
    shadowSize: "중형",
    location: "고래바다",
    times: ["새벽", "낮", "밤"],
    weathers: ["상시"],
    sellMin: 155,
    sellMax: 1240,
    grades: grades([155, 232, 310, 620, 1240]),
  },
  {
    id: "giant-halibut",
    emoji: "🐟",
    // thumbnail: "/images/fishes/giant-halibut.png",
    name: "Giant Halibut",
    ko: "대문짝넙치",
    level: 4,
    fishType: "바다",
    shadowSize: "금색",
    location: "바다낚시",
    times: ["상시"],
    weathers: ["무지개"],
    sellMin: 320,
    sellMax: 2560,
    grades: grades([320, 480, 640, 1280, 2560]),
  },
  {
    id: "atlantic-pygmy-octopus",
    emoji: "🐙",
    // thumbnail: "/images/fishes/atlantic-pygmy-octopus.png",
    name: "Atlantic Pygmy Octopus",
    ko: "대서양난쟁이문어",
    level: 4,
    fishType: "바다",
    shadowSize: "소형",
    location: "잔잔한 바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 150,
    sellMax: 1200,
    grades: grades([150, 225, 300, 600, 1200]),
  },

  // Lv.5 - 강
  {
    id: "freshwater-blenny",
    emoji: "🐟",
    // thumbnail: "/images/fishes/freshwater-blenny.png",
    name: "Freshwater Blenny",
    ko: "민물배도라치",
    level: 5,
    fishType: "강",
    shadowSize: "소형",
    location: "노을강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 150,
    sellMax: 1200,
    grades: grades([150, 225, 300, 600, 1200]),
  },

  // Lv.5 - 호수
  {
    id: "trout",
    emoji: "🐟",
    // thumbnail: "/images/fishes/trout.png",
    name: "Trout",
    ko: "송어",
    level: 5,
    fishType: "호수",
    shadowSize: "중형",
    location: "초원 호수",
    times: ["새벽", "밤"],
    weathers: ["맑음", "무지개"],
    sellMin: 230,
    sellMax: 1840,
    grades: grades([230, 345, 460, 920, 1840]),
  },
  {
    id: "rudd",
    emoji: "🐟",
    // thumbnail: "/images/fishes/rudd.png",
    name: "Rudd",
    ko: "루드",
    level: 5,
    fishType: "호수",
    shadowSize: "소형",
    location: "근교 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 150,
    sellMax: 1200,
    grades: grades([150, 225, 300, 600, 1200]),
  },

  // Lv.5 - 바다
  {
    id: "atlantic-mackerel",
    emoji: "🐟",
    // thumbnail: "/images/fishes/atlantic-mackerel.png",
    name: "Atlantic Mackerel",
    ko: "대서양고등어",
    level: 5,
    fishType: "바다",
    shadowSize: "소형",
    location: "고래바다",
    times: ["낮", "밤"],
    weathers: ["맑음", "무지개"],
    sellMin: 150,
    sellMax: 1200,
    grades: grades([150, 225, 300, 600, 1200]),
  },
  {
    id: "european-lobster",
    emoji: "🦞",
    // thumbnail: "/images/fishes/european-lobster.png",
    name: "European Lobster",
    ko: "유럽가재",
    level: 5,
    fishType: "바다",
    shadowSize: "금색",
    location: "잔잔한 바다",
    times: ["새벽", "밤"],
    weathers: ["상시"],
    sellMin: 230,
    sellMax: 1840,
    grades: grades([230, 345, 460, 920, 1840]),
  },
  {
    id: "european-flying-squid",
    emoji: "🦑",
    thumbnail: "/images/fishes/european_flying_squid.png",
    name: "European Flying Squid",
    ko: "유럽날오징어",
    level: 5,
    fishType: "바다",
    shadowSize: "금색",
    location: "바다낚시",
    times: ["상시"],
    weathers: ["무지개"],
    sellMin: 320,
    sellMax: 2560,
    grades: grades([320, 480, 640, 1280, 2560]),
  },

  // Lv.6 - 강
  {
    id: "chum-salmon",
    emoji: "🐟",
    // thumbnail: "/images/fishes/chum-salmon.png",
    name: "Chum Salmon",
    ko: "첨 연어",
    level: 6,
    fishType: "강",
    shadowSize: "소형",
    location: "고요한 강",
    times: ["상시"],
    weathers: ["무지개"],
    sellMin: 150,
    sellMax: 1200,
    grades: grades([150, 225, 300, 600, 1200]),
  },

  // Lv.6 - 호수
  {
    id: "giant-freshwater-pearl-mussel",
    emoji: "🐚",
    // thumbnail: "/images/fishes/giant-freshwater-pearl-mussel.png",
    name: "Giant Freshwater Pearl Mussel",
    ko: "큰진주조개",
    level: 6,
    fishType: "호수",
    shadowSize: "중형",
    location: "숲속 호수",
    times: ["상시"],
    weathers: ["무지개"],
    sellMin: 380,
    sellMax: 3040,
    grades: grades([380, 570, 760, 1520, 3040]),
  },
  {
    id: "sarugi",
    emoji: "🐟",
    // thumbnail: "/images/fishes/sarugi.png",
    name: "Sarugi",
    ko: "사루기",
    level: 6,
    fishType: "호수",
    shadowSize: "중형",
    location: "근교 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 230,
    sellMax: 1840,
    grades: grades([230, 345, 460, 920, 1840]),
  },

  // Lv.6 - 바다
  {
    id: "pufferfish",
    emoji: "🐡",
    // thumbnail: "/images/fishes/pufferfish.png",
    name: "Pufferfish",
    ko: "복어",
    level: 6,
    fishType: "바다",
    shadowSize: "중형",
    location: "구해",
    times: ["낮", "밤"],
    weathers: ["상시"],
    sellMin: 230,
    sellMax: 1840,
    grades: grades([230, 345, 460, 920, 1840]),
  },
  {
    id: "luminous-roughy",
    emoji: "🐟",
    // thumbnail: "/images/fishes/luminous-roughy.png",
    name: "Luminous Roughy",
    ko: "등불성대",
    level: 6,
    fishType: "바다",
    shadowSize: "중형",
    location: "동해",
    times: ["상시"],
    weathers: ["무지개"],
    sellMin: 380,
    sellMax: 3040,
    grades: grades([380, 570, 760, 1520, 3040]),
  },
  {
    id: "smallspotted-catshark",
    emoji: "🦈",
    // thumbnail: "/images/fishes/smallspotted-catshark.png",
    name: "Smallspotted Catshark",
    ko: "두툽상어",
    level: 6,
    fishType: "바다",
    shadowSize: "금색",
    location: "바다낚시",
    times: ["상시"],
    weathers: ["무지개"],
    sellMin: 535,
    sellMax: 4280,
    grades: grades([535, 802, 1070, 2140, 4280]),
  },

  // Lv.7 - 강
  {
    id: "three-spined-stickleback",
    emoji: "🐟",
    // thumbnail: "/images/fishes/three-spined-stickleback.png",
    name: "Three-spined Stickleback",
    ko: "큰가시고기",
    level: 7,
    fishType: "강",
    shadowSize: "소형",
    location: "얕은 강",
    times: ["상시"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 150,
    sellMax: 1200,
    grades: grades([150, 225, 300, 600, 1200]),
  },

  // Lv.7 - 호수
  {
    id: "striped-killifish",
    emoji: "🐟",
    // thumbnail: "/images/fishes/striped-killifish.png",
    name: "Striped Killifish",
    ko: "줄무늬송사리",
    level: 7,
    fishType: "호수",
    shadowSize: "소형",
    location: "근교 호수",
    times: ["새벽", "밤"],
    weathers: ["맑음", "무지개"],
    sellMin: 150,
    sellMax: 1200,
    grades: grades([150, 225, 300, 600, 1200]),
  },
  {
    id: "sculpin",
    emoji: "🐟",
    // thumbnail: "/images/fishes/sculpin.png",
    name: "Sculpin",
    ko: "둑중개",
    level: 7,
    fishType: "호수",
    shadowSize: "소형",
    location: "온천 산수",
    times: ["낮", "밤"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 150,
    sellMax: 1200,
    grades: grades([150, 225, 300, 600, 1200]),
  },

  // Lv.7 - 바다
  {
    id: "oarfish",
    emoji: "🐟",
    // thumbnail: "/images/fishes/oarfish.png",
    name: "Oarfish",
    ko: "산갈치",
    level: 7,
    fishType: "바다",
    shadowSize: "금색",
    location: "바다낚시",
    times: ["아침", "낮"],
    weathers: ["무지개"],
    sellMin: 535,
    sellMax: 4280,
    grades: grades([535, 802, 1070, 2140, 4280]),
  },
  {
    id: "european-eel",
    emoji: "🐟",
    // thumbnail: "/images/fishes/european-eel.png",
    name: "European Eel",
    ko: "유럽장어",
    level: 7,
    fishType: "바다",
    shadowSize: "중형",
    location: "구해",
    times: ["아침", "낮", "밤"],
    weathers: ["무지개"],
    sellMin: 380,
    sellMax: 3040,
    grades: grades([380, 570, 760, 1520, 3040]),
  },
  {
    id: "blackspot-seabream",
    emoji: "🐟",
    // thumbnail: "/images/fishes/blackspot-seabream.png",
    name: "Blackspot Seabream",
    ko: "검은점돔",
    level: 7,
    fishType: "바다",
    shadowSize: "중형",
    location: "잔잔한 바다",
    times: ["새벽", "밤"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 230,
    sellMax: 1840,
    grades: grades([230, 345, 460, 920, 1840]),
  },

  // Lv.8 - 호수
  {
    id: "pearl-fish",
    emoji: "🐟",
    // thumbnail: "/images/fishes/pearl-fish.png",
    name: "Pearl Fish",
    ko: "펄고기",
    level: 8,
    fishType: "호수",
    shadowSize: "소형",
    location: "근교 호수",
    times: ["밤", "새벽", "아침"],
    weathers: ["맑음", "무지개"],
    sellMin: 250,
    sellMax: 2000,
    grades: grades([250, 375, 500, 1000, 2000]),
  },
  {
    id: "northern-blue-crayfish",
    emoji: "🦞",
    // thumbnail: "/images/fishes/northern-blue-crayfish.png",
    name: "Northern Blue Crayfish",
    ko: "북유럽파란가재",
    level: 8,
    fishType: "호수",
    shadowSize: "소형",
    location: "숲속 호수",
    times: ["새벽", "밤"],
    weathers: ["상시"],
    sellMin: 250,
    sellMax: 2000,
    grades: grades([250, 375, 500, 1000, 2000]),
  },

  // Lv.8 - 바다
  {
    id: "golden-king-crab",
    emoji: "🦀",
    // thumbnail: "/images/fishes/golden-king-crab.png",
    name: "Golden King Crab",
    ko: "황금 킹크랩",
    level: 8,
    fishType: "바다",
    shadowSize: "금색",
    location: "바다낚시",
    times: ["상시"],
    weathers: ["무지개"],
    sellMin: 850,
    sellMax: 6800,
    grades: grades([850, 1275, 1700, 3400, 6800]),
  },
  {
    id: "king-crab",
    emoji: "🦀",
    // thumbnail: "/images/fishes/king-crab.png",
    name: "King Crab",
    ko: "킹크랩",
    level: 8,
    fishType: "바다",
    shadowSize: "대형",
    location: "고래바다",
    times: ["아침", "낮", "밤"],
    weathers: ["무지개"],
    sellMin: 535,
    sellMax: 4280,
    grades: grades([535, 802, 1070, 2140, 4280]),
  },
  {
    id: "cod",
    emoji: "🐟",
    // thumbnail: "/images/fishes/cod.png",
    name: "Cod",
    ko: "대구",
    level: 8,
    fishType: "바다",
    shadowSize: "중형",
    location: "동해",
    times: ["새벽", "밤"],
    weathers: ["맑음", "무지개"],
    sellMin: 230,
    sellMax: 1840,
    grades: grades([230, 345, 460, 920, 1840]),
  },

  // Lv.9 - 강
  {
    id: "huchen",
    emoji: "🐟",
    // thumbnail: "/images/fishes/huchen.png",
    name: "Huchen",
    ko: "후첸",
    level: 9,
    fishType: "강",
    shadowSize: "중형",
    location: "거목강",
    times: ["새벽", "밤"],
    weathers: ["무지개"],
    sellMin: 380,
    sellMax: 3040,
    grades: grades([380, 570, 760, 1520, 3040]),
  },

  // Lv.9 - 호수
  {
    id: "river-pike",
    emoji: "🐟",
    // thumbnail: "/images/fishes/river-pike.png",
    name: "River Pike",
    ko: "강꼬치고기",
    level: 9,
    fishType: "호수",
    shadowSize: "중형",
    location: "근교 호수",
    times: ["새벽", "밤"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 610,
    sellMax: 4880,
    grades: grades([610, 915, 1220, 2440, 4880]),
  },
  {
    id: "pumpkinseed",
    emoji: "🐟",
    // thumbnail: "/images/fishes/pumpkinseed.png",
    name: "Pumpkinseed",
    ko: "펌프킨시드",
    level: 9,
    fishType: "호수",
    shadowSize: "소형",
    location: "온천 산수",
    times: ["낮", "밤"],
    weathers: ["맑음", "무지개"],
    sellMin: 250,
    sellMax: 2000,
    grades: grades([250, 375, 500, 1000, 2000]),
  },

  // Lv.9 - 바다
  {
    id: "ocean-sunfish",
    emoji: "🐟",
    // thumbnail: "/images/fishes/ocean-sunfish.png",
    name: "Ocean Sunfish",
    ko: "개복치",
    level: 9,
    fishType: "바다",
    shadowSize: "대형",
    location: "동해",
    times: ["새벽", "아침", "낮"],
    weathers: ["상시"],
    sellMin: 850,
    sellMax: 6800,
    grades: grades([850, 1275, 1700, 3400, 6800]),
  },
  {
    id: "bluefin-tuna",
    emoji: "🐟",
    // thumbnail: "/images/fishes/bluefin-tuna.png",
    name: "Bluefin Tuna",
    ko: "참다랑어",
    level: 9,
    fishType: "바다",
    shadowSize: "대형",
    location: "잔잔한 바다",
    times: ["아침", "낮"],
    weathers: ["무지개"],
    sellMin: 850,
    sellMax: 6800,
    grades: grades([850, 1275, 1700, 3400, 6800]),
  },
  {
    id: "opah",
    emoji: "🐟",
    // thumbnail: "/images/fishes/opah.png",
    name: "Opah",
    ko: "붉은개복치",
    level: 9,
    fishType: "바다",
    shadowSize: "금색",
    location: "바다낚시",
    times: ["새벽", "밤"],
    weathers: ["무지개"],
    sellMin: 850,
    sellMax: 6800,
    grades: grades([850, 1275, 1700, 3400, 6800]),
  },

  // Lv.10 - 호수
  {
    id: "arctic-char",
    emoji: "🐟",
    // thumbnail: "/images/fishes/arctic-char.png",
    name: "Arctic Char",
    ko: "북극곤들매기",
    level: 10,
    fishType: "호수",
    shadowSize: "중형",
    location: "숲속 호수",
    times: ["낮", "밤"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 610,
    sellMax: 4880,
    grades: grades([610, 915, 1220, 2440, 4880]),
  },
  {
    id: "european-catfish",
    emoji: "🐟",
    // thumbnail: "/images/fishes/european-catfish.png",
    name: "European Catfish",
    ko: "유럽메기",
    level: 10,
    fishType: "호수",
    shadowSize: "중형",
    location: "초원 호수",
    times: ["새벽", "밤"],
    weathers: ["맑음", "무지개"],
    sellMin: 610,
    sellMax: 4880,
    grades: grades([610, 915, 1220, 2440, 4880]),
  },
  {
    id: "bluegill",
    emoji: "🐟",
    // thumbnail: "/images/fishes/bluegill.png",
    name: "Bluegill",
    ko: "블루길",
    level: 10,
    fishType: "호수",
    shadowSize: "소형",
    location: "온천 산수",
    times: ["새벽", "밤"],
    weathers: ["맑음", "무지개"],
    sellMin: 395,
    sellMax: 3160,
    grades: grades([395, 592, 790, 1580, 3160]),
  },

  // Lv.10 - 바다
  {
    id: "swordfish",
    emoji: "🐟",
    // thumbnail: "/images/fishes/swordfish.png",
    name: "Swordfish",
    ko: "황새치",
    level: 10,
    fishType: "바다",
    shadowSize: "대형",
    location: "고래바다",
    times: ["아침", "낮"],
    weathers: ["무지개"],
    sellMin: 850,
    sellMax: 6800,
    grades: grades([850, 1275, 1700, 3400, 6800]),
  },
  {
    id: "hammerhead-shark",
    emoji: "🦈",
    // thumbnail: "/images/fishes/hammerhead-shark.png",
    name: "Hammerhead Shark",
    ko: "귀상어",
    level: 10,
    fishType: "바다",
    shadowSize: "대형",
    location: "구해",
    times: ["새벽", "밤"],
    weathers: ["무지개"],
    sellMin: 850,
    sellMax: 6800,
    grades: grades([850, 1275, 1700, 3400, 6800]),
  },
  {
    id: "mako-shark",
    emoji: "🦈",
    // thumbnail: "/images/fishes/mako-shark.png",
    name: "Mako Shark",
    ko: "청상아리",
    level: 10,
    fishType: "바다",
    shadowSize: "금색",
    location: "바다낚시",
    times: ["아침", "낮"],
    weathers: ["무지개"],
    sellMin: 850,
    sellMax: 6800,
    grades: grades([850, 1275, 1700, 3400, 6800]),
  },
];
