// ── Types ─────────────────────────────────────────────────────────────────────

export type FishType = "강" | "호수" | "바다";

export interface Fish {
  id: string;
  emoji: string;
  thumbnail: string;
  name: string;
  ko: string;
  desc?: string;
  level: number;
  weathers: string[];
  times: string[];
  location: string;
}

export interface FishGrade {
  stars: number;
  sellPrice: number;
  sellEventPrice: number;
}

export interface FishDetail extends Fish {
  fishType: FishType;
  shadowSize: string;
  sellMin: number;
  sellMax: number;
  grades: FishGrade[];
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function grades(prices: [number, number, number, number, number]): FishGrade[] {
  return prices.map((price, i) => ({
    stars: i + 1,
    sellPrice: price,
    sellEventPrice: 0,
  }));
}

// ── Data ──────────────────────────────────────────────────────────────────────

export const FISHES: FishDetail[] = [
  // 강 - Lv.1
  {
    id: "freshwater-bass",
    emoji: "🐟",
    thumbnail: "/images/fishing/freshwater-bass.png",
    name: "Freshwater Bass",
    ko: "민물배스",
    level: 1,
    fishType: "강",
    shadowSize: "중형",
    location: "모든 강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 75,
    sellMax: 600,
    grades: grades([75, 112, 150, 300, 600]),
  },
  {
    id: "sky-loach",
    emoji: "🐟",
    thumbnail: "/images/fishing/sky-loach.png",
    name: "Sky Loach",
    ko: "하늘종개",
    level: 1,
    fishType: "강",
    shadowSize: "소형",
    location: "거목강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "barbel",
    emoji: "🐟",
    thumbnail: "/images/fishing/barbel.png",
    name: "Barbel",
    ko: "바벨",
    level: 1,
    fishType: "강",
    shadowSize: "중형",
    location: "얕은 강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 75,
    sellMax: 600,
    grades: grades([75, 112, 150, 300, 600]),
  },
  {
    id: "largemouth-bass",
    emoji: "🐟",
    thumbnail: "/images/fishing/largemouth-bass.png",
    name: "Largemouth Bass",
    ko: "큰얼룩배스",
    level: 1,
    fishType: "강",
    shadowSize: "소형",
    location: "노을강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "minnow",
    emoji: "🐟",
    thumbnail: "/images/fishing/minnow.png",
    name: "Minnow",
    ko: "미노우",
    level: 1,
    fishType: "강",
    shadowSize: "소형",
    location: "고요한 강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "giant-shrimp",
    emoji: "🦐",
    thumbnail: "/images/fishing/giant-shrimp.png",
    name: "Giant Shrimp",
    ko: "왕새우",
    level: 1,
    fishType: "강",
    shadowSize: "소형",
    location: "모든 강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },

  // 강 - Lv.3
  {
    id: "freshwater-zander",
    emoji: "🐟",
    thumbnail: "/images/fishing/freshwater-zander.png",
    name: "Freshwater Zander",
    ko: "민물잰더",
    level: 3,
    fishType: "강",
    shadowSize: "중형",
    location: "거목강",
    times: ["상시"],
    weathers: ["맑음", "무지개"],
    sellMin: 230,
    sellMax: 1840,
    grades: grades([230, 345, 460, 920, 1840]),
  },

  // 강 - Lv.4
  {
    id: "european-carp",
    emoji: "🐟",
    thumbnail: "/images/fishing/european-carp.png",
    name: "European Carp",
    ko: "유럽잉어",
    level: 4,
    fishType: "강",
    shadowSize: "중형",
    location: "노을강",
    times: ["낮", "밤"],
    weathers: ["맑음", "무지개"],
    sellMin: 230,
    sellMax: 1840,
    grades: grades([230, 345, 460, 920, 1840]),
  },
  {
    id: "freshwater-cod",
    emoji: "🐟",
    thumbnail: "/images/fishing/freshwater-cod.png",
    name: "Freshwater Cod",
    ko: "민물대구",
    level: 4,
    fishType: "강",
    shadowSize: "중형",
    location: "고요한 강",
    times: ["낮", "밤"],
    weathers: ["상시"],
    sellMin: 230,
    sellMax: 1840,
    grades: grades([230, 345, 460, 920, 1840]),
  },
  {
    id: "piranha",
    emoji: "🐟",
    thumbnail: "/images/fishing/piranha.png",
    name: "Piranha",
    ko: "레드밸리피라냐",
    level: 4,
    fishType: "강",
    shadowSize: "중형",
    location: "거목강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 230,
    sellMax: 1840,
    grades: grades([230, 345, 460, 920, 1840]),
  },

  // 호수 - Lv.1
  {
    id: "european-frog",
    emoji: "🐸",
    thumbnail: "/images/fishing/european-frog.png",
    name: "European Frog",
    ko: "유럽참개구리",
    level: 1,
    fishType: "호수",
    shadowSize: "파랑",
    location: "모든 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 320,
    sellMax: 2560,
    grades: grades([320, 480, 640, 1280, 2560]),
  },
  {
    id: "european-chub",
    emoji: "🐟",
    thumbnail: "/images/fishing/european-chub.png",
    name: "European Chub",
    ko: "유럽처브",
    level: 1,
    fishType: "호수",
    shadowSize: "중형",
    location: "모든 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 75,
    sellMax: 600,
    grades: grades([75, 112, 150, 300, 600]),
  },
  {
    id: "tench",
    emoji: "🐟",
    thumbnail: "/images/fishing/tench.png",
    name: "Tench",
    ko: "텐치",
    level: 1,
    fishType: "호수",
    shadowSize: "소형",
    location: "숲속 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "arctic-salmon",
    emoji: "🐟",
    thumbnail: "/images/fishing/arctic-salmon.png",
    name: "Arctic Salmon",
    ko: "극지연어",
    level: 1,
    fishType: "호수",
    shadowSize: "중형",
    location: "온천 산수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 105,
    sellMax: 840,
    grades: grades([105, 157, 210, 420, 840]),
  },
  {
    id: "crucian-carp",
    emoji: "🐟",
    thumbnail: "/images/fishing/crucian-carp.png",
    name: "Crucian Carp",
    ko: "붕어",
    level: 1,
    fishType: "호수",
    shadowSize: "중형",
    location: "근교 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 75,
    sellMax: 600,
    grades: grades([75, 112, 150, 300, 600]),
  },
  {
    id: "european-bleak",
    emoji: "🐟",
    thumbnail: "/images/fishing/european-bleak.png",
    name: "European Bleak",
    ko: "유럽백조어",
    level: 1,
    fishType: "호수",
    shadowSize: "소형",
    location: "모든 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "bleak",
    emoji: "🐟",
    thumbnail: "/images/fishing/bleak.png",
    name: "Bleak",
    ko: "백조어",
    level: 1,
    fishType: "호수",
    shadowSize: "소형",
    location: "근교 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },

  // 호수 - Lv.2
  {
    id: "stone-minnow",
    emoji: "🐟",
    thumbnail: "/images/fishing/stone-minnow.png",
    name: "Stone Minnow",
    ko: "돌마자",
    level: 2,
    fishType: "호수",
    shadowSize: "소형",
    location: "근교 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },
  {
    id: "mud-sunfish",
    emoji: "🐟",
    thumbnail: "/images/fishing/mud-sunfish.png",
    name: "Mud Sunfish",
    ko: "머드개복치",
    level: 2,
    fishType: "호수",
    shadowSize: "소형",
    location: "숲속 호수",
    times: ["아침", "낮", "밤"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },
  {
    id: "sea-smelt",
    emoji: "🐟",
    thumbnail: "/images/fishing/sea-smelt.png",
    name: "Sea Smelt",
    ko: "바다빙어",
    level: 2,
    fishType: "호수",
    shadowSize: "소형",
    location: "초원 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },
  {
    id: "plum-bass",
    emoji: "🐟",
    thumbnail: "/images/fishing/plum-bass.png",
    name: "Plum Bass",
    ko: "매화농어",
    level: 2,
    fishType: "호수",
    shadowSize: "소형",
    location: "온천 산수",
    times: ["낮", "밤"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },

  // 호수 - Lv.3
  {
    id: "mussel",
    emoji: "🐚",
    thumbnail: "/images/fishing/mussel.png",
    name: "Mussel",
    ko: "홍합",
    level: 3,
    fishType: "호수",
    shadowSize: "소형",
    location: "근교 호수",
    times: ["상시"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },
  {
    id: "tadpole",
    emoji: "🐸",
    thumbnail: "/images/fishing/tadpole.png",
    name: "Tadpole",
    ko: "올챙이",
    level: 3,
    fishType: "호수",
    shadowSize: "소형",
    location: "온천 산수",
    times: ["상시"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },
  {
    id: "european-crayfish",
    emoji: "🦞",
    thumbnail: "/images/fishing/european-crayfish.png",
    name: "European Crayfish",
    ko: "유럽민물가재",
    level: 3,
    fishType: "호수",
    shadowSize: "중형",
    location: "숲속 호수",
    times: ["새벽", "아침", "밤"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },

  // 호수 - Lv.4
  {
    id: "bigmouth-bass",
    emoji: "🐟",
    thumbnail: "/images/fishing/bigmouth-bass.png",
    name: "Bigmouth Bass",
    ko: "큰입배스",
    level: 4,
    fishType: "호수",
    shadowSize: "중형",
    location: "숲속 호수",
    times: ["상시"],
    weathers: ["맑음", "무지개"],
    sellMin: 230,
    sellMax: 1840,
    grades: grades([230, 345, 460, 920, 1840]),
  },
  {
    id: "freshwater-crab",
    emoji: "🦀",
    thumbnail: "/images/fishing/freshwater-crab.png",
    name: "Freshwater Crab",
    ko: "민물게",
    level: 4,
    fishType: "호수",
    shadowSize: "소형",
    location: "근교 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },
  {
    id: "butterfly-carp",
    emoji: "🐟",
    thumbnail: "/images/fishing/butterfly-carp.png",
    name: "Butterfly Carp",
    ko: "나비잉어",
    level: 4,
    fishType: "호수",
    shadowSize: "대형",
    location: "초원 호수",
    times: ["상시"],
    weathers: ["비", "눈", "무지개"],
    sellMin: 320,
    sellMax: 2560,
    grades: grades([320, 480, 640, 1280, 2560]),
  },

  // 바다 - Lv.1
  {
    id: "sea-bass",
    emoji: "🐟",
    thumbnail: "/images/fishing/sea-bass.png",
    name: "Sea Bass",
    ko: "배스",
    level: 1,
    fishType: "바다",
    shadowSize: "중형",
    location: "모든 바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 75,
    sellMax: 600,
    grades: grades([75, 112, 150, 300, 600]),
  },
  {
    id: "skipjack-tuna",
    emoji: "🐟",
    thumbnail: "/images/fishing/skipjack-tuna.png",
    name: "Skipjack Tuna",
    ko: "가다랑어",
    level: 1,
    fishType: "바다",
    shadowSize: "대형",
    location: "모든 바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 210,
    sellMax: 1680,
    grades: grades([210, 315, 420, 840, 1680]),
  },
  {
    id: "hairtail",
    emoji: "🐟",
    thumbnail: "/images/fishing/hairtail.png",
    name: "Hairtail",
    ko: "갈치",
    level: 1,
    fishType: "바다",
    shadowSize: "대형",
    location: "잔잔한 바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 105,
    sellMax: 840,
    grades: grades([105, 157, 210, 420, 840]),
  },
  {
    id: "sea-shrimp",
    emoji: "🦐",
    thumbnail: "/images/fishing/sea-shrimp.png",
    name: "Sea Shrimp",
    ko: "바다새우",
    level: 1,
    fishType: "바다",
    shadowSize: "소형",
    location: "동해",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "horse-mackerel",
    emoji: "🐟",
    thumbnail: "/images/fishing/horse-mackerel.png",
    name: "Horse Mackerel",
    ko: "전갱이",
    level: 1,
    fishType: "바다",
    shadowSize: "소형",
    location: "고래바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },

  // 바다 - Lv.2
  {
    id: "atlantic-silver-shark",
    emoji: "🦈",
    thumbnail: "/images/fishing/atlantic-silver-shark.png",
    name: "Atlantic Silver Shark",
    ko: "대서양은상어",
    level: 2,
    fishType: "바다",
    shadowSize: "소형",
    location: "모든 바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 320,
    sellMax: 2560,
    grades: grades([320, 480, 640, 1280, 2560]),
  },
  {
    id: "sea-stickleback",
    emoji: "🐟",
    thumbnail: "/images/fishing/sea-stickleback.png",
    name: "Sea Stickleback",
    ko: "바다가시고기",
    level: 2,
    fishType: "바다",
    shadowSize: "소형",
    location: "구해",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "yellow-goatfish",
    emoji: "🐟",
    thumbnail: "/images/fishing/yellow-goatfish.png",
    name: "Yellow Goatfish",
    ko: "노랑촉수",
    level: 2,
    fishType: "바다",
    shadowSize: "금색",
    location: "바다낚시",
    times: ["상시"],
    weathers: ["무지개"],
    sellMin: 320,
    sellMax: 2560,
    grades: grades([320, 480, 640, 1280, 2560]),
  },

  // 바다 - Lv.3
  {
    id: "yellow-scad",
    emoji: "🐟",
    thumbnail: "/images/fishing/yellow-scad.png",
    name: "Yellow Scad",
    ko: "노란전갱이",
    level: 3,
    fishType: "바다",
    shadowSize: "중형",
    location: "잔잔한 바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 155,
    sellMax: 1240,
    grades: grades([155, 232, 310, 620, 1240]),
  },
  {
    id: "seahorse",
    emoji: "🐟",
    thumbnail: "/images/fishing/seahorse.png",
    name: "Seahorse",
    ko: "해마",
    level: 3,
    fishType: "바다",
    shadowSize: "소형",
    location: "고래바다",
    times: ["새벽", "아침", "낮"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },
  {
    id: "monkfish",
    emoji: "🐟",
    thumbnail: "/images/fishing/monkfish.png",
    name: "Monkfish",
    ko: "아귀",
    level: 3,
    fishType: "바다",
    shadowSize: "금색",
    location: "바다낚시",
    times: ["상시"],
    weathers: ["무지개"],
    sellMin: 320,
    sellMax: 2560,
    grades: grades([320, 480, 640, 1280, 2560]),
  },
  {
    id: "hermit-crab",
    emoji: "🦀",
    thumbnail: "/images/fishing/hermit-crab.png",
    name: "Hermit Crab",
    ko: "소라게",
    level: 3,
    fishType: "바다",
    shadowSize: "소형",
    location: "동해",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },
  {
    id: "clownfish",
    emoji: "🐟",
    thumbnail: "/images/fishing/clownfish.png",
    name: "Clownfish",
    ko: "흰동가리",
    level: 3,
    fishType: "바다",
    shadowSize: "소형",
    location: "구해",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 100,
    sellMax: 800,
    grades: grades([100, 150, 200, 400, 800]),
  },

  // 바다 - Lv.4
  {
    id: "goby",
    emoji: "🐟",
    thumbnail: "/images/fishing/goby.png",
    name: "Goby",
    ko: "망둥어",
    level: 4,
    fishType: "바다",
    shadowSize: "소형",
    location: "동해",
    times: ["아침", "낮"],
    weathers: ["상시"],
    sellMin: 150,
    sellMax: 1200,
    grades: grades([150, 225, 300, 600, 1200]),
  },
  {
    id: "common-octopus",
    emoji: "🐙",
    thumbnail: "/images/fishing/common-octopus.png",
    name: "Common Octopus",
    ko: "참문어",
    level: 4,
    fishType: "바다",
    shadowSize: "금색",
    location: "바다낚시",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 320,
    sellMax: 2560,
    grades: grades([320, 480, 640, 1280, 2560]),
  },
  {
    id: "atlantic-salmon",
    emoji: "🐟",
    thumbnail: "/images/fishing/atlantic-salmon.png",
    name: "Atlantic Salmon",
    ko: "대서양연어",
    level: 4,
    fishType: "바다",
    shadowSize: "중형",
    location: "고래바다",
    times: ["새벽", "낮", "밤"],
    weathers: ["상시"],
    sellMin: 155,
    sellMax: 1240,
    grades: grades([155, 232, 310, 620, 1240]),
  },
  {
    id: "giant-halibut",
    emoji: "🐟",
    thumbnail: "/images/fishing/giant-halibut.png",
    name: "Giant Halibut",
    ko: "대문짝넙치",
    level: 4,
    fishType: "바다",
    shadowSize: "금색",
    location: "바다낚시",
    times: ["상시"],
    weathers: ["무지개"],
    sellMin: 320,
    sellMax: 2560,
    grades: grades([320, 480, 640, 1280, 2560]),
  },
  {
    id: "atlantic-pygmy-octopus",
    emoji: "🐙",
    thumbnail: "/images/fishing/atlantic-pygmy-octopus.png",
    name: "Atlantic Pygmy Octopus",
    ko: "대서양난쟁이문어",
    level: 4,
    fishType: "바다",
    shadowSize: "소형",
    location: "잔잔한 바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 150,
    sellMax: 1200,
    grades: grades([150, 225, 300, 600, 1200]),
  },
];
