// ── Types ─────────────────────────────────────────────────────────────────────

export type FishType = "강" | "호수" | "바다";

export interface Fish {
  id: string;
  emoji: string;
  thumbnail: string;
  name: string;
  ko: string;
  desc?: string;
  level: number;
  weathers: string[];
  times: string[];
  location: string;
}

export interface FishGrade {
  stars: number;
  sellPrice: number;
  sellEventPrice: number;
}

export interface FishDetail extends Fish {
  fishType: FishType;
  shadowSize: string;
  sellMin: number;
  sellMax: number;
  grades: FishGrade[];
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function grades(prices: [number, number, number, number, number]): FishGrade[] {
  return prices.map((price, i) => ({
    stars: i + 1,
    sellPrice: price,
    sellEventPrice: 0,
  }));
}

// ── Data ──────────────────────────────────────────────────────────────────────

export const FISHES: FishDetail[] = [
  // 강
  {
    id: "freshwater-bass",
    emoji: "🐟",
    thumbnail: "/images/fishing/freshwater-bass.png",
    name: "Freshwater Bass",
    ko: "민물배스",
    level: 1,
    fishType: "강",
    shadowSize: "중형",
    location: "모든 강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 75,
    sellMax: 600,
    grades: grades([75, 112, 150, 300, 600]),
  },
  {
    id: "sky-loach",
    emoji: "🐟",
    thumbnail: "/images/fishing/sky-loach.png",
    name: "Sky Loach",
    ko: "하늘종개",
    level: 1,
    fishType: "강",
    shadowSize: "소형",
    location: "거목강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "barbel",
    emoji: "🐟",
    thumbnail: "/images/fishing/barbel.png",
    name: "Barbel",
    ko: "바벨",
    level: 1,
    fishType: "강",
    shadowSize: "중형",
    location: "얕은 강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 75,
    sellMax: 600,
    grades: grades([75, 112, 150, 300, 600]),
  },
  {
    id: "largemouth-bass",
    emoji: "🐟",
    thumbnail: "/images/fishing/largemouth-bass.png",
    name: "Largemouth Bass",
    ko: "큰얼룩배스",
    level: 1,
    fishType: "강",
    shadowSize: "소형",
    location: "노을강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "minnow",
    emoji: "🐟",
    thumbnail: "/images/fishing/minnow.png",
    name: "Minnow",
    ko: "미노우",
    level: 1,
    fishType: "강",
    shadowSize: "소형",
    location: "고요한 강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "giant-shrimp",
    emoji: "🦐",
    thumbnail: "/images/fishing/giant-shrimp.png",
    name: "Giant Shrimp",
    ko: "왕새우",
    level: 1,
    fishType: "강",
    shadowSize: "소형",
    location: "모든 강",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },

  // 호수
  {
    id: "european-frog",
    emoji: "🐸",
    thumbnail: "/images/fishing/european-frog.png",
    name: "European Frog",
    ko: "유럽참개구리",
    level: 1,
    fishType: "호수",
    shadowSize: "파랑",
    location: "모든 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 320,
    sellMax: 2560,
    grades: grades([320, 480, 640, 1280, 2560]),
  },
  {
    id: "european-chub",
    emoji: "🐟",
    thumbnail: "/images/fishing/european-chub.png",
    name: "European Chub",
    ko: "유럽처브",
    level: 1,
    fishType: "호수",
    shadowSize: "중형",
    location: "모든 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 75,
    sellMax: 600,
    grades: grades([75, 112, 150, 300, 600]),
  },
  {
    id: "tench",
    emoji: "🐟",
    thumbnail: "/images/fishing/tench.png",
    name: "Tench",
    ko: "텐치",
    level: 1,
    fishType: "호수",
    shadowSize: "소형",
    location: "숲속 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "arctic-salmon",
    emoji: "🐟",
    thumbnail: "/images/fishing/arctic-salmon.png",
    name: "Arctic Salmon",
    ko: "극지연어",
    level: 1,
    fishType: "호수",
    shadowSize: "중형",
    location: "온천 산수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 105,
    sellMax: 840,
    grades: grades([105, 157, 210, 420, 840]),
  },
  {
    id: "crucian-carp",
    emoji: "🐟",
    thumbnail: "/images/fishing/crucian-carp.png",
    name: "Crucian Carp",
    ko: "붕어",
    level: 1,
    fishType: "호수",
    shadowSize: "중형",
    location: "근교 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 75,
    sellMax: 600,
    grades: grades([75, 112, 150, 300, 600]),
  },
  {
    id: "european-bleak",
    emoji: "🐟",
    thumbnail: "/images/fishing/european-bleak.png",
    name: "European Bleak",
    ko: "유럽백조어",
    level: 1,
    fishType: "호수",
    shadowSize: "소형",
    location: "모든 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "bleak",
    emoji: "🐟",
    thumbnail: "/images/fishing/bleak.png",
    name: "Bleak",
    ko: "백조어",
    level: 1,
    fishType: "호수",
    shadowSize: "소형",
    location: "근교 호수",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },

  // 바다
  {
    id: "sea-bass",
    emoji: "🐟",
    thumbnail: "/images/fishing/sea-bass.png",
    name: "Sea Bass",
    ko: "배스",
    level: 1,
    fishType: "바다",
    shadowSize: "중형",
    location: "모든 바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 75,
    sellMax: 600,
    grades: grades([75, 112, 150, 300, 600]),
  },
  {
    id: "skipjack-tuna",
    emoji: "🐟",
    thumbnail: "/images/fishing/skipjack-tuna.png",
    name: "Skipjack Tuna",
    ko: "가다랑어",
    level: 1,
    fishType: "바다",
    shadowSize: "대형",
    location: "모든 바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 210,
    sellMax: 1680,
    grades: grades([210, 315, 420, 840, 1680]),
  },
  {
    id: "hairtail",
    emoji: "🐟",
    thumbnail: "/images/fishing/hairtail.png",
    name: "Hairtail",
    ko: "갈치",
    level: 1,
    fishType: "바다",
    shadowSize: "대형",
    location: "잔잔한 바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 105,
    sellMax: 840,
    grades: grades([105, 157, 210, 420, 840]),
  },
  {
    id: "sea-shrimp",
    emoji: "🦐",
    thumbnail: "/images/fishing/sea-shrimp.png",
    name: "Sea Shrimp",
    ko: "바다새우",
    level: 1,
    fishType: "바다",
    shadowSize: "소형",
    location: "동해",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
  {
    id: "horse-mackerel",
    emoji: "🐟",
    thumbnail: "/images/fishing/horse-mackerel.png",
    name: "Horse Mackerel",
    ko: "전갱이",
    level: 1,
    fishType: "바다",
    shadowSize: "소형",
    location: "고래바다",
    times: ["상시"],
    weathers: ["상시"],
    sellMin: 50,
    sellMax: 400,
    grades: grades([50, 75, 100, 200, 400]),
  },
];
